use super::*;

mod lanes;
pub(crate) mod outcomes;

pub(crate) use outcomes::DeferredOutcomeAggregator;
pub use outcomes::DeferredOutcomeHandle;

#[derive(Clone, Copy, Debug)]
struct RcApplyAction {
    op_idx: usize,
    pba: Pba,
    delta: i64,
    standalone_refcount: bool,
    remap_freed_candidate: bool,
    /// True when this action is generated by an `L2pRemapRange` apply
    /// rather than a per-LBA `L2pRemap`. The post-apply refcount
    /// merger pushes freed pbas into `L2pRemapRange.freed_pbas: Vec`
    /// when set, vs. assigning `L2pRemap.freed_pba: Option<Pba>` when
    /// clear.
    range_op: bool,
}

/// One unit of work in an L2P shard's bucket. The pre-existing path
/// stored only op indices and the apply re-inspected each op; with the
/// addition of [`WalOp::L2pRemapRange`] a single op can target many
/// LBAs that map to different L2P shards, so the bucket plan needs to
/// carry per-shard slice info as well.
#[derive(Clone, Debug)]
pub(super) enum L2pBucketEntry {
    /// Per-LBA op (`L2pPut`, `L2pDelete`, or `L2pRemap`). Apply looks
    /// up `ops[op_idx]` and dispatches by variant.
    Single(usize),
    /// One L2P shard's slice of a `WalOp::L2pRemapRange`. `lba_offsets`
    /// indexes into the op's `values` slice. A range op crossing 2
    /// shards produces two `RangeSlice` entries (one per shard) sharing
    /// the same `op_idx`; the outcome merger combines their partial
    /// `L2pRemapRange` results.
    RangeSlice {
        op_idx: usize,
        lba_offsets: Box<[u32]>,
    },
}

impl L2pBucketEntry {
    fn op_idx(&self) -> usize {
        match self {
            L2pBucketEntry::Single(idx) => *idx,
            L2pBucketEntry::RangeSlice { op_idx, .. } => *op_idx,
        }
    }
}

struct L2pBucketApplyResult {
    outcomes: Vec<(usize, ApplyOutcome)>,
    rc_actions: Vec<RcApplyAction>,
}

#[derive(Default)]
struct RcBucketApplyResult {
    refcount_outcomes: Vec<(usize, u32)>,
    /// `(op_idx, pba, range_op)` — `range_op = true` means the freed
    /// pba should be appended to the op's `L2pRemapRange.freed_pbas`
    /// Vec; `false` means it sets `L2pRemap.freed_pba: Option<Pba>`.
    remap_freed: Vec<(usize, Pba, bool)>,
}

/// Land an L2P bucket's per-op outcome into the `outcomes` vec. For
/// `L2pRemapRange` outcomes that may have been split across multiple
/// shard lanes, merge with any partial outcome already at the slot:
/// per-LBA `applied` bits are OR-ed, `prevs` slots are filled in where
/// previously `None`, and `freed_pbas` are concatenated. All other
/// outcomes are 1-shard-per-op and simply overwrite.
fn merge_l2p_outcome(outcomes: &mut [Option<ApplyOutcome>], idx: usize, incoming: ApplyOutcome) {
    match incoming {
        ApplyOutcome::L2pRemapRange {
            applied: in_applied,
            prevs: in_prevs,
            freed_pbas: in_freed,
        } => match outcomes[idx].take() {
            None => {
                outcomes[idx] = Some(ApplyOutcome::L2pRemapRange {
                    applied: in_applied,
                    prevs: in_prevs,
                    freed_pbas: in_freed,
                });
            }
            Some(ApplyOutcome::L2pRemapRange {
                applied: mut existing_applied,
                prevs: existing_prevs,
                mut freed_pbas,
            }) => {
                debug_assert_eq!(existing_applied.len(), in_applied.len());
                debug_assert_eq!(existing_prevs.len(), in_prevs.len());
                let mut merged_prevs = existing_prevs.into_vec();
                let in_prevs_vec = in_prevs.into_vec();
                for (i, slot) in merged_prevs.iter_mut().enumerate() {
                    if in_applied[i] {
                        existing_applied[i] = true;
                    }
                    if slot.is_none() && in_prevs_vec[i].is_some() {
                        *slot = in_prevs_vec[i];
                    }
                }
                freed_pbas.extend(in_freed);
                outcomes[idx] = Some(ApplyOutcome::L2pRemapRange {
                    applied: existing_applied,
                    prevs: merged_prevs.into_boxed_slice(),
                    freed_pbas,
                });
            }
            Some(other) => {
                panic!("L2pRemapRange partial at idx={idx} but existing outcome is {other:?}");
            }
        },
        other => {
            outcomes[idx] = Some(other);
        }
    }
}

struct LaneDispatchPlan {
    l2p_sorted: Vec<((VolumeOrdinal, usize), Vec<L2pBucketEntry>)>,
    rc_buckets: Vec<Vec<RcApplyAction>>,
    rc_enqueued: Vec<bool>,
    /// Dedup op indices grouped by shard. Outer length always equals
    /// `Db::dedup_lanes.len()`; an empty inner vec means that shard
    /// has no work in this commit and gets no `DispatchLaneKey::Dedup`
    /// footprint entry.
    dedup_buckets: Vec<Vec<usize>>,
}

struct QueuedLanePlan {
    ops: Arc<Vec<WalOp>>,
    /// BFG this commit is stamped to. Threaded into the rc/dedup apply
    /// closures so `rc.stage(bfg, …)` lands the derived refcount delta in
    /// the same BFG ring slot as the commit's L2P buffer insert — the
    /// refcount fold must be keyed to the same `checkpoint_lsn` prefix as
    /// L2P or onyx's replay re-derivation double-counts (see
    /// `refcount::shard`). The commit thread holds its `BfgGuard` across
    /// `apply_ops_laned` (it awaits every rc/dedup receiver), so the slot
    /// cannot roll to Syncing while these stages run.
    bfg: crate::types::Bfg,
    l2p_receivers: Vec<crossbeam_channel::Receiver<Result<L2pBucketApplyResult>>>,
    rc_buckets: Vec<Vec<RcApplyAction>>,
    /// Per-shard dedup op indices. Drained into the per-shard apply
    /// closures during `apply_ops_laned`.
    dedup_buckets: Vec<Vec<usize>>,
    /// One pending slot per non-empty bucket (entries for empty
    /// buckets are `None`).
    dedup_pendings: Vec<Option<PendingApplyWork>>,
}

#[derive(Clone, Copy, Debug, Default)]
struct LanedApplyTiming {
    l2p_wait: std::time::Duration,
    rc_enqueue: std::time::Duration,
    rc_wait: std::time::Duration,
    dedup_enqueue: std::time::Duration,
    dedup_wait: std::time::Duration,
}

#[derive(Clone, Copy, Debug, Default)]
struct CommitTiming {
    drop_gate_wait: std::time::Duration,
    plan: std::time::Duration,
    encode: std::time::Duration,
    wal_submit: std::time::Duration,
    dispatch_wait: std::time::Duration,
    apply_gate_wait: std::time::Duration,
    lane_enqueue: std::time::Duration,
    apply: std::time::Duration,
    laned: LanedApplyTiming,
    finish_global_wait: std::time::Duration,
}

struct CommitApplyContext<'a> {
    commit_started: std::time::Instant,
    cpu_started: Option<std::time::Duration>,
    timing: CommitTiming,
    volumes: HashMap<VolumeOrdinal, Arc<Volume>>,
    serial_apply: bool,
    plan: Option<LaneDispatchPlan>,
    plan_l2p_lanes: usize,
    plan_rc_lanes: usize,
    plan_dedup_ops: usize,
    dispatch_lanes: usize,
    ops: &'a [WalOp],
    /// BFG: the BFG that the committing thread
    /// pinned via [`crate::bfg::BfgStateMachine::enter`]. Threads down
    /// into every L2pBuffer write so the slot stamp matches the slot
    /// the [`crate::bfg::BfgGuard`] is keeping alive.
    bfg: crate::types::Bfg,
}

pub(super) struct ActiveApplyGuard<'a> {
    db: &'a Db,
    lsn: Lsn,
}

impl Drop for ActiveApplyGuard<'_> {
    fn drop(&mut self) {
        self.db.active_apply_lsns.lock().remove(&self.lsn);
    }
}

impl DispatchFootprint {
    pub(super) fn global() -> Self {
        Self {
            global: true,
            lanes: BTreeSet::new(),
        }
    }

    fn from_lane_plan(plan: &LaneDispatchPlan) -> Self {
        let mut lanes = BTreeSet::new();
        for ((vol_ord, sid), _) in &plan.l2p_sorted {
            lanes.insert(DispatchLaneKey::L2p(*vol_ord, *sid));
        }
        for (sid, enqueued) in plan.rc_enqueued.iter().copied().enumerate() {
            if enqueued {
                lanes.insert(DispatchLaneKey::Refcount(sid));
            }
        }
        for (sid, bucket) in plan.dedup_buckets.iter().enumerate() {
            if !bucket.is_empty() {
                lanes.insert(DispatchLaneKey::Dedup(sid as u32));
            }
        }
        Self {
            global: false,
            lanes,
        }
    }

    fn conflicts(&self, other: &Self) -> bool {
        self.global || other.global || self.lanes.iter().any(|lane| other.lanes.contains(lane))
    }
}

#[cfg(any(target_os = "linux", target_os = "android"))]
fn thread_cpu_time() -> Option<std::time::Duration> {
    let mut ts = std::mem::MaybeUninit::<libc::timespec>::uninit();
    let rc = unsafe { libc::clock_gettime(libc::CLOCK_THREAD_CPUTIME_ID, ts.as_mut_ptr()) };
    if rc != 0 {
        return None;
    }
    let ts = unsafe { ts.assume_init() };
    Some(std::time::Duration::new(
        ts.tv_sec as u64,
        ts.tv_nsec as u32,
    ))
}

#[cfg(not(any(target_os = "linux", target_os = "android")))]
fn thread_cpu_time() -> Option<std::time::Duration> {
    None
}

fn duration_us(duration: std::time::Duration) -> u64 {
    duration.as_micros().min(u128::from(u64::MAX)) as u64
}

fn dispatch_ready(state: &DispatchState, lsn: Lsn) -> bool {
    let Some(entry) = state.pending.get(&lsn) else {
        return false;
    };
    entry.durable
        && state
            .pending
            .range(..lsn)
            .all(|(_, lower)| !entry.footprint.conflicts(&lower.footprint))
}

impl Db {
    // -------- transaction / commit --------------------------------------

    /// Start a new transaction that buffers ops until `commit()`.
    pub fn begin(&self) -> Transaction<'_> {
        Transaction::new(self)
    }

    /// LSN of the most recent successful commit.
    pub fn last_applied_lsn(&self) -> Lsn {
        *self.last_applied_lsn.lock()
    }

    /// Status-only variant backed by a non-blocking mirror so external
    /// observation never waits on commit apply.
    pub fn last_applied_lsn_best_effort(&self) -> Lsn {
        self.last_applied_lsn_observed
            .load(std::sync::atomic::Ordering::Relaxed)
    }

    pub(super) fn enter_active_apply(&self, lsn: Lsn) -> ActiveApplyGuard<'_> {
        self.active_apply_lsns.lock().insert(lsn);
        ActiveApplyGuard { db: self, lsn }
    }

    fn has_higher_active_apply(&self, lsn: Lsn) -> bool {
        self.active_apply_lsns
            .lock()
            .iter()
            .next_back()
            .is_some_and(|active| *active > lsn)
    }

    pub(super) fn acquire_commit_apply_gate(&self, lsn: Lsn) -> crate::apply_gate::ReadGuard<'_> {
        const RECHECK: std::time::Duration = std::time::Duration::from_micros(100);

        let started = std::time::Instant::now();
        let mut logged_wait = false;
        loop {
            if !self.apply_gate.has_writer_pending() {
                return self.apply_gate.read();
            }

            if self.has_higher_active_apply(lsn) {
                let waited = started.elapsed();
                if waited >= std::time::Duration::from_millis(1) {
                    tracing::debug!(
                        lsn,
                        wait_us = duration_us(waited),
                        "metadb: lower-LSN commit bypassing pending checkpoint to unblock global apply order"
                    );
                }
                return self.apply_gate.read_bypass_writer_pending();
            }

            if !logged_wait && started.elapsed() >= std::time::Duration::from_secs(1) {
                logged_wait = true;
                tracing::warn!(
                    lsn,
                    wait_ms = started.elapsed().as_millis() as u64,
                    "metadb: commit waiting behind checkpoint apply gate"
                );
            }
            std::thread::sleep(RECHECK);
        }
    }

    /// Internal: submit a set of ops to the WAL, apply them to indexes,
    /// and return the assigned LSN plus any per-op outcomes.
    ///
    /// Concurrency: WAL submission runs **outside** any Db-level lock so
    /// multiple submitters coalesce into one group-commit batch at the
    /// WAL writer. After fsync, dispatch is re-serialised by global LSN
    /// but does only short enqueue work: bucket ops, push each bucket into
    /// its shard lane, and advance `last_dispatched_lsn`. The expensive
    /// apply work then runs concurrently across lanes. A commit only waits
    /// for global LSN order again after its lanes finish, right before it
    /// advances the contiguous `last_applied_lsn`.
    pub(crate) fn commit_ops(&self, ops: &[WalOp]) -> Result<(Lsn, Vec<ApplyOutcome>)> {
        if ops.is_empty() {
            self.metrics.record_commit_empty();
            return Ok((self.last_applied_lsn(), Vec::new()));
        }
        let commit_started = std::time::Instant::now();
        let cpu_started = thread_cpu_time();
        let mut timing = CommitTiming::default();
        self.metrics.record_commit_attempt(ops.len());
        // `drop_gate.read()` pairs with lifecycle paths' write acquire.
        // Hold it across submit + apply so `drop_snapshot` /
        // `range_delete` cannot wedge themselves between our LSN
        // assignment and apply. Using the read side is important:
        // ordinary commits must still submit concurrently so the WAL
        // writer can coalesce them into group commits.
        let drop_gate_started = std::time::Instant::now();
        let _drop_guard = self.drop_gate.read();
        timing.drop_gate_wait = drop_gate_started.elapsed();
        self.metrics
            .record_commit_drop_gate_wait(timing.drop_gate_wait);
        // Plan the lane footprint before LSN allocation. `submit_wal_ops`
        // registers this footprint while the WAL set still holds its
        // allocator mutex, so every lower LSN's footprint is known before
        // a higher LSN can be assigned.
        let unlogged_commit_guard = if self.unlogged_commits_enabled {
            let unlogged_gate_started = std::time::Instant::now();
            let guard = self.unlogged_commit_gate.write();
            self.metrics
                .record_commit_unlogged_gate_wait(unlogged_gate_started.elapsed());
            let checkpoint_started = std::time::Instant::now();
            self.checkpoint_unlogged_before_wal_commit()?;
            self.metrics
                .record_commit_checkpoint_unlogged(checkpoint_started.elapsed());
            Some(guard)
        } else {
            None
        };
        let plan_started = std::time::Instant::now();
        let volumes = self.volumes.read().clone();
        let serial_apply = self.batch_uses_serial_apply(ops);
        let plan = if serial_apply {
            None
        } else {
            match self.build_lane_dispatch_plan(&volumes, ops) {
                Ok(plan) => Some(plan),
                Err(err) => {
                    self.metrics.record_commit_error(commit_started.elapsed());
                    self.poison_commit_waiters(&err);
                    return Err(err);
                }
            }
        };
        timing.plan = plan_started.elapsed();
        self.metrics.record_commit_plan(timing.plan);
        let plan_l2p_lanes = plan.as_ref().map(|plan| plan.l2p_sorted.len()).unwrap_or(0);
        let plan_rc_lanes = plan
            .as_ref()
            .map(|plan| {
                plan.rc_enqueued
                    .iter()
                    .filter(|enqueued| **enqueued)
                    .count()
            })
            .unwrap_or(0);
        let plan_dedup_ops = plan
            .as_ref()
            .map(|plan| {
                plan.dedup_buckets
                    .iter()
                    .map(|bucket| bucket.len())
                    .sum::<usize>()
            })
            .unwrap_or(0);
        let dispatch_footprint = plan
            .as_ref()
            .map(DispatchFootprint::from_lane_plan)
            .unwrap_or_else(DispatchFootprint::global);
        let dispatch_lanes = dispatch_footprint.lanes.len();

        // Buffer-mode commit path: data-plane ops have no metadb-side
        // durable footprint (recovery comes from onyx's LV2 buffer);
        // only promotion records — which the buffer cannot
        // synthesise — get folded into the lifecycle journal here.
        // For every other op we simply allocate an LSN via
        // `reserve_unlogged` so apply ordering / dispatch tracking
        // stays consistent.
        //
        // BFG: acquire a BfgGuard BEFORE the
        // LSN reservation so the slot stamp is locked in before the
        // allocator can hand out a higher LSN to a later BFG. The
        // guard's drop (at function exit) decrements the slot's
        // inflight counter, which is what the `BfgQuiesceThread`
        // parks on. Holding it across the apply also means
        // `take_syncing_slot` cannot race with this commit's tree
        // mutations because the slot stays pinned (state == Open or
        // Quiescing — never Syncing while inflight > 0).
        let _bfg_guard = self.bfg.enter();
        let wal_started = std::time::Instant::now();
        let lsn = {
            let result = self.lsn_alloc.reserve(|lsn| {
                self.register_dispatch_intent(lsn, dispatch_footprint);
            });
            timing.wal_submit = wal_started.elapsed();
            self.metrics.record_commit_wal_submit(timing.wal_submit);
            match result {
                Ok(lsn) => lsn,
                Err(err) => {
                    self.metrics.record_commit_error(commit_started.elapsed());
                    self.poison_commit_waiters(&err);
                    return Err(err);
                }
            }
        };
        _bfg_guard.record_lsn(lsn);
        drop(unlogged_commit_guard);
        if let Err(err) = self.faults.inject(FaultPoint::CommitPostWalBeforeApply) {
            self.metrics.record_commit_error(commit_started.elapsed());
            self.poison_commit_waiters(&err);
            return Err(err);
        }

        // Wait until every lower durable-or-in-flight LSN that touches one
        // of our lanes has dispatched. Disjoint lower LSNs do not block us.
        let wait_started = std::time::Instant::now();
        if let Err(err) = self.mark_wal_durable_and_wait_for_dispatch(lsn) {
            timing.dispatch_wait = wait_started.elapsed();
            self.metrics.record_commit_apply_wait(timing.dispatch_wait);
            self.metrics.record_commit_error(commit_started.elapsed());
            return Err(err);
        }
        timing.dispatch_wait = wait_started.elapsed();
        self.metrics.record_commit_apply_wait(timing.dispatch_wait);

        self.finish_commit_apply(
            lsn,
            CommitApplyContext {
                commit_started,
                cpu_started,
                timing,
                volumes,
                serial_apply,
                plan,
                plan_l2p_lanes,
                plan_rc_lanes,
                plan_dedup_ops,
                dispatch_lanes,
                ops,
                bfg: _bfg_guard.bfg(),
            },
            "metadb: slow commit_with_outcomes (>=1s)",
        )
    }

    /// BFG entry point. Same WAL + apply pipeline as
    /// [`Self::commit_ops`], but the returned outcome `Vec` is parked
    /// in the [`DeferredOutcomeAggregator`] keyed by the freshly
    /// assigned LSN and delivered through the
    /// [`DeferredOutcomeHandle`] later — once the L2P compactor's
    /// per-pass drain confirms every `(volume, shard)` the batch
    /// touched has been folded into the on-disk tree. Equivalent to
    /// `commit_ops` followed by an immediate-release on the handle
    /// when `Config::commit_deferred_outcomes_enabled = false`, so
    /// callers can route through the deferred surface unconditionally
    /// and let configuration decide whether outcomes arrive at the
    /// caller thread or at the next compactor cycle. The on-disk
    /// state observed by readers is identical in both modes — only
    /// outcome *delivery* shifts.
    pub fn commit_ops_deferred(&self, ops: &[WalOp]) -> Result<(Lsn, DeferredOutcomeHandle)> {
        // Empty op batch — return the no-work LSN immediately. Matches
        // the `commit_ops` early-out at line ~382 of this file.
        if ops.is_empty() {
            self.metrics.record_commit_empty();
            let lsn = self.last_applied_lsn();
            return Ok((lsn, DeferredOutcomeHandle::ready(lsn, Ok(Vec::new()))));
        }

        // BFG: route through the WAL with
        // `synchronous=false` IFF both and flags are
        // enabled. Async WAL on the inline outcome path is an untested
        // Buffer-as-sole-journal lifecycle journal cutover retired the WAL writer, so
        // there is no sync/async fsync choice to thread through any
        // more — every commit runs the same path. The `wal_async_*`
        // flag is preserved on `Config` as dead-but-accepted so older
        // call sites don't break.
        let (lsn, outcomes) = self.commit_ops(ops)?;

        // Choose delivery mode based on the live config flag.
        let handle = if self.commit_deferred_outcomes_enabled {
            // The compactor's per-pass drain releases this entry once
            // its `last_applied_lsn` watermark catches up. See
            // [`crate::db::commit::outcomes`].
            self.deferred_outcomes.stage(lsn, outcomes)
        } else {
            // Flag off — deliver immediately so callers see
            // sync-path latency. Compile-in infrastructure stays
            // routed through the deferred surface so the same call
            // site works in both modes.
            DeferredOutcomeHandle::ready(lsn, Ok(outcomes))
        };

        Ok((lsn, handle))
    }

    /// Experimental: apply a batch without writing a WAL record.
    ///
    /// The caller must keep its own durable replay source until a later
    /// metadb checkpoint makes this LSN durable. Onyx uses LV2 write-buffer
    /// entries for that source.
    pub fn commit_ops_unlogged(&self, ops: &[WalOp]) -> Result<(Lsn, Vec<ApplyOutcome>)> {
        if ops.is_empty() {
            self.metrics.record_commit_empty();
            return Ok((self.last_applied_lsn(), Vec::new()));
        }
        if !self.unlogged_commits_enabled {
            return Err(MetaDbError::InvalidArgument(
                "unlogged commits are disabled in this metadb config".into(),
            ));
        }
        let commit_started = std::time::Instant::now();
        let cpu_started = thread_cpu_time();
        let mut timing = CommitTiming::default();
        self.metrics.record_commit_attempt(ops.len());

        let drop_gate_started = std::time::Instant::now();
        let _drop_guard = self.drop_gate.read();
        timing.drop_gate_wait = drop_gate_started.elapsed();
        self.metrics
            .record_commit_drop_gate_wait(timing.drop_gate_wait);
        let unlogged_gate_started = std::time::Instant::now();
        let _unlogged_commit_guard = self.unlogged_commit_gate.read();
        self.metrics
            .record_commit_unlogged_gate_wait(unlogged_gate_started.elapsed());

        let plan_started = std::time::Instant::now();
        let volumes = self.volumes.read().clone();
        let serial_apply = self.batch_uses_serial_apply(ops);
        let plan = if serial_apply {
            None
        } else {
            match self.build_lane_dispatch_plan(&volumes, ops) {
                Ok(plan) => Some(plan),
                Err(err) => {
                    self.metrics.record_commit_error(commit_started.elapsed());
                    self.poison_commit_waiters(&err);
                    return Err(err);
                }
            }
        };
        timing.plan = plan_started.elapsed();
        self.metrics.record_commit_plan(timing.plan);
        let plan_l2p_lanes = plan.as_ref().map(|plan| plan.l2p_sorted.len()).unwrap_or(0);
        let plan_rc_lanes = plan
            .as_ref()
            .map(|plan| {
                plan.rc_enqueued
                    .iter()
                    .filter(|enqueued| **enqueued)
                    .count()
            })
            .unwrap_or(0);
        let plan_dedup_ops = plan
            .as_ref()
            .map(|plan| {
                plan.dedup_buckets
                    .iter()
                    .map(|bucket| bucket.len())
                    .sum::<usize>()
            })
            .unwrap_or(0);
        let dispatch_footprint = plan
            .as_ref()
            .map(DispatchFootprint::from_lane_plan)
            .unwrap_or_else(DispatchFootprint::global);
        let dispatch_lanes = dispatch_footprint.lanes.len();

        // BFG: same BfgGuard pattern as
        // commit_ops_with_options. Acquire before WAL reserve to preserve
        // the LSN-monotonicity invariant across the unlogged path.
        let _bfg_guard = self.bfg.enter();
        let dispatch_started = std::time::Instant::now();
        let lsn = match self.lsn_alloc.reserve(|lsn| {
            self.register_dispatch_intent(lsn, dispatch_footprint);
        }) {
            Ok(lsn) => lsn,
            Err(err) => {
                self.metrics.record_commit_error(commit_started.elapsed());
                self.poison_commit_waiters(&err);
                return Err(err);
            }
        };
        _bfg_guard.record_lsn(lsn);
        if let Err(err) = self.mark_wal_durable_and_wait_for_dispatch(lsn) {
            timing.dispatch_wait = dispatch_started.elapsed();
            self.metrics.record_commit_apply_wait(timing.dispatch_wait);
            self.metrics.record_commit_error(commit_started.elapsed());
            return Err(err);
        }
        timing.dispatch_wait = dispatch_started.elapsed();
        self.metrics.record_commit_apply_wait(timing.dispatch_wait);

        let result = self.finish_commit_apply(
            lsn,
            CommitApplyContext {
                commit_started,
                cpu_started,
                timing,
                volumes,
                serial_apply,
                plan,
                plan_l2p_lanes,
                plan_rc_lanes,
                plan_dedup_ops,
                dispatch_lanes,
                ops,
                bfg: _bfg_guard.bfg(),
            },
            "metadb: slow unlogged commit_with_outcomes (>=1s)",
        );
        if result.is_ok() {
            let mut pending = self.unlogged_pending_lsn.lock();
            *pending = Some(pending.map_or(lsn, |prev| prev.max(lsn)));
        }
        result
    }

    /// Buffer-mode staging path. Identical apply semantics to
    /// [`commit_ops_unlogged`] but skips:
    ///
    ///   * `register_dispatch_intent` — the dispatch_state per-LSN
    ///     pending map is purely a serialisation handle for the lane
    ///     path; stage runs apply on the caller thread, so there is no
    ///     lane to coordinate.
    ///   * `mark_wal_durable_and_wait_for_dispatch` — the 614 µs/commit
    ///     wait observed on nvme-box. With no lane dispatch, there is
    ///     nothing to wait on.
    ///   * `acquire_commit_apply_gate` / `enter_active_apply` — the
    ///     apply_gate read side is defence-in-depth against flush's
    ///     manifest-commit write side; buffer-mode apply already
    ///     serialises on each shard's `tree.write()` (via
    ///     `force_compact_l2p_buffers` during sync) so the read gate
    ///     is redundant for this path.
    ///
    /// What still happens — `finish_global_apply(lsn)` is REQUIRED:
    /// `last_applied_lsn` is a contiguous-prefix watermark fed by
    /// `applied_set` pops. Lifecycle ops (PromotionChunk / FreePbas /
    /// range_delete / DropSnapshot) park on
    /// `wait_for_global_apply_turn(lsn)` until the watermark covers
    /// `lsn - 1`. Skipping `finish_global_apply` would leave gaps in
    /// the prefix and any later lifecycle op would wait forever.
    ///

    /// What still happens, preserving correctness:
    ///
    ///   * `drop_gate.read()` — keeps lifecycle ops (drop_snapshot /
    ///     drop_volume / clone_volume / range_delete / create_volume /
    ///     take_snapshot) from racing with our apply. Lifecycle paths
    ///     hold `drop_gate.write()` across their forced BFG sync and
    ///     plan-then-apply, so they observe a quiesced state.
    ///   * `BfgGuard` pinned **before** LSN allocation. The
    ///     `closing_open` flag in `BfgStateMachine::roll_to_quiescing`
    ///     blocks new `enter()` while a roll is mid-drain, preserving
    ///     `max(LSN in BFG_n) <= min(LSN in BFG_n+1)`. This is the
    ///     invariant `wal_checkpoint = slot_max_lsn(bfg)` relies on.
    ///   * `lsn_alloc.reserve(|_| {})` — bumps the global LSN counter
    ///     under a brief mutex. The callback is a no-op (no dispatch
    ///     intent registration).
    ///   * `apply_commit_batch` — synchronous apply, identical to
    ///     `commit_ops`'s serial-fallback path. For batches ≥ 8 ops
    ///     it routes through `apply_ops_grouped` (per-shard bucketing).
    ///     For smaller batches and snapshot-bearing volumes it loops
    ///     `apply_op_bare`.
    ///
    /// Idempotency under onyx LV2 buffer replay:
    ///
    ///   * L2P: `L2pValue::seq` guards `apply_l2p_bucket_buffer` —
    ///     stale-seq replays are rejected and produce no buffer
    ///     mutation.
    ///   * Refcount: `RcShard::stage` has a page_lsn-based replay-skip
    ///     for entries whose target page already reflects this LSN.
    ///   * Dedup: `apply_dedup_*_with_rc` reads the current value
    ///     before mutating; same-LSN replays are no-ops.
    ///
    /// This is the **hot path** for onyx writes: the writer batches
    /// dozens to hundreds of `L2pRemap` + `DedupPut` ops per call.
    /// The savings vs `commit_ops_unlogged` is the per-call dispatch
    /// wait (~614 µs at j16d32 randwrite on the nvme-box baseline);
    /// the apply work itself is unchanged.
    pub fn stage_ops(&self, ops: &[WalOp]) -> Result<(Lsn, Vec<ApplyOutcome>)> {
        if ops.is_empty() {
            self.metrics.record_commit_empty();
            return Ok((self.last_applied_lsn(), Vec::new()));
        }
        let stage_started = std::time::Instant::now();
        self.metrics.record_commit_attempt(ops.len());

        let drop_gate_started = std::time::Instant::now();
        let _drop_guard = self.drop_gate.read();
        self.metrics
            .record_commit_drop_gate_wait(drop_gate_started.elapsed());

        let volumes = self.volumes.read().clone();

        // BfgGuard before LSN reserve: the `closing_open` invariant
        // (bfg/mod.rs) blocks `enter()` during a roll's drain, so any
        // LSN we allocate is bounded above by every later BFG's LSNs.
        let _bfg_guard = self.bfg.enter();
        let lsn_started = std::time::Instant::now();
        let lsn = match self.lsn_alloc.reserve(|_| {}) {
            Ok(lsn) => lsn,
            Err(err) => {
                self.metrics.record_commit_error(stage_started.elapsed());
                self.poison_commit_waiters(&err);
                return Err(err);
            }
        };
        self.metrics.record_commit_wal_submit(lsn_started.elapsed());
        _bfg_guard.record_lsn(lsn);

        let apply_started = std::time::Instant::now();
        let outcomes = match self.apply_commit_batch(&volumes, lsn, _bfg_guard.bfg(), ops) {
            Ok(outcomes) => outcomes,
            Err(err) => {
                self.metrics.record_commit_apply(apply_started.elapsed());
                self.metrics.record_commit_error(stage_started.elapsed());
                self.poison_commit_waiters(&err);
                return Err(err);
            }
        };
        self.metrics.record_commit_apply(apply_started.elapsed());

        // Bump the contiguous-prefix watermark via applied_set. Without
        // this, lifecycle ops parking on `wait_for_global_apply_turn`
        // would stall forever — their LSN would always be `> applied + 1`
        // because the staged LSNs never enter `applied_set`. The
        // `finish_global_apply` call itself only touches in-memory
        // counters; it does not interact with dispatch_state.
        let finish_started = std::time::Instant::now();
        if let Err(err) = self.finish_global_apply(lsn) {
            self.metrics.record_commit_error(stage_started.elapsed());
            return Err(err);
        }
        // stage_ops is the buffer-direct hot path; the laned path records
        // this via `record_commit_finish_global_wait` but stage_ops did
        // not, leaving the global watermark-bump cost (last_applied_lsn +
        // applied_set mutexes) folded into the opaque apply bucket.
        self.metrics
            .record_commit_finish_global_wait(finish_started.elapsed());
        self.metrics.record_commit_success(stage_started.elapsed());
        Ok((lsn, outcomes))
    }

    /// BFG eligibility check.
    ///
    /// The L2P-direct fast path can carry a commit iff:
    ///   * no dedup bucket carries work — dedup apply lives in its own
    ///     per-shard lane and isn't re-implementable on the caller
    ///     thread without serialising every dedup lane;
    ///   * no rc shard is flagged in `rc_enqueued` — guarded
    ///     `L2pRemap` (the only L2P op that touches rc at plan time)
    ///     reads rc inline inside `apply_l2p_bucket_buffer`, but if rc
    ///     work is pending in this batch we route through lanes for
    ///     consistency with the existing `apply_ops_laned` ordering;
    ///   * every target (vol, sid) L2P shard runs in `use_buffer`
    ///     mode. Buffer mode emits zero `rc_actions`; tree mode does
    ///     not and cannot be bypassed here.
    ///
    /// This is intentionally borrowing — the caller still owns
    /// `plan` after the check and can route it to either path.
    fn plan_is_l2p_direct_eligible(
        plan: &LaneDispatchPlan,
        volumes: &HashMap<VolumeOrdinal, Arc<Volume>>,
    ) -> bool {
        if plan.dedup_buckets.iter().any(|bucket| !bucket.is_empty()) {
            return false;
        }
        if plan.rc_enqueued.iter().any(|&enq| enq) {
            return false;
        }
        for ((vol_ord, sid), _entries) in &plan.l2p_sorted {
            let Some(volume) = volumes.get(vol_ord) else {
                return false;
            };
            let Some(shard) = volume.shards.get(*sid) else {
                return false;
            };
            if !shard.use_buffer {
                return false;
            }
        }
        true
    }

    /// BFG direct apply.
    ///
    /// Mirrors what `enqueue_lane_plan` + the L2P recv loop of
    /// `apply_ops_laned` would do, but runs every per-shard
    /// `apply_l2p_bucket_buffer` invocation in series on the calling
    /// commit thread. Each invocation is read-mostly on `read_view`
    /// and writes only into `shard.l2p_buffer` (a `parking_lot::Mutex`
    /// briefly held per LBA), so no shared apply-lane scheduler is
    /// needed. Every shard is touched once; ordering across shards is
    /// independent (different `(vol, sid)` keys disjoint).
    ///
    /// Eligibility guarantees:
    ///   * `apply_l2p_bucket_buffer` returns empty `rc_actions` (its
    ///     buffer-mode body never pushes any); we `debug_assert!` and
    ///     return an error if not, since that would indicate a future
    ///     change broke the contract.
    ///   * Every op index in `ops` ends up populated in `outcomes`:
    ///     `L2pPut`/`L2pDelete`/`L2pRemap` produce one outcome from
    ///     one bucket; `L2pRemapRange` may span multiple buckets and
    ///     gets merged via `merge_l2p_outcome`.
    fn apply_l2p_direct(
        &self,
        volumes: &HashMap<VolumeOrdinal, Arc<Volume>>,
        lsn: Lsn,
        bfg: crate::types::Bfg,
        plan: LaneDispatchPlan,
        ops: &[WalOp],
    ) -> Result<Vec<ApplyOutcome>> {
        let mut outcome_slots: Vec<Option<ApplyOutcome>> = (0..ops.len()).map(|_| None).collect();
        // Snapshot rc shard handles once (cheap clones of Arcs).
        // Only the guarded-`L2pRemap` path inside `apply_l2p_bucket_buffer`
        // dereferences this; eligibility filters that case out, but
        // the helper still takes the slice as a parameter.
        let refcount_shards_snapshot: Vec<Arc<crate::refcount::RcShard>> =
            self.refcount_shards.iter().map(|s| s.rc.clone()).collect();

        for ((vol_ord, sid), entries) in plan.l2p_sorted {
            let volume = volumes.get(&vol_ord).ok_or_else(|| {
                MetaDbError::Corruption(format!(
                    "apply_l2p_direct: missing volume ord {vol_ord} at apply time"
                ))
            })?;
            let bucket_result = Self::apply_l2p_bucket_buffer(
                volume.clone(),
                sid,
                entries,
                lsn,
                bfg,
                ops,
                &refcount_shards_snapshot,
                &self.metrics,
                self.rc_authoritative_reclaim,
            )?;
            // Direct apply is only reached when `plan_is_l2p_direct_eligible`
            // (no rc-enqueued shards). Under rc-authoritative every
            // Put/Remap/RemapRange marks rc → such a commit is NOT direct
            // eligible → routed to the lane path. So the only ops that reach
            // here are rc-neutral (L2pDelete / empty) → rc_actions stays empty.
            debug_assert!(
                bucket_result.rc_actions.is_empty(),
                "apply_l2p_bucket_buffer in direct apply produced non-empty rc_actions; \
                 a rc-marking op slipped past plan_is_l2p_direct_eligible"
            );
            if !bucket_result.rc_actions.is_empty() {
                return Err(MetaDbError::Corruption(
                    "direct apply received rc_actions from buffer-mode L2P bucket; \
                     fallback to lane path required"
                        .into(),
                ));
            }
            for (idx, outcome) in bucket_result.outcomes {
                merge_l2p_outcome(&mut outcome_slots, idx, outcome);
            }
        }

        let outcomes: Vec<ApplyOutcome> = outcome_slots
            .into_iter()
            .enumerate()
            .map(|(idx, slot)| {
                slot.ok_or_else(|| {
                    MetaDbError::Corruption(format!(
                        "apply_l2p_direct: op index {idx} not covered by any L2P bucket"
                    ))
                })
            })
            .collect::<Result<Vec<_>>>()?;
        Ok(outcomes)
    }

    fn finish_commit_apply(
        &self,
        lsn: Lsn,
        mut ctx: CommitApplyContext<'_>,
        slow_message: &'static str,
    ) -> Result<(Lsn, Vec<ApplyOutcome>)> {
        let apply_gate_started = std::time::Instant::now();
        let apply_guard = self.acquire_commit_apply_gate(lsn);
        let read_held_started = std::time::Instant::now();
        let active_apply = self.enter_active_apply(lsn);
        ctx.timing.apply_gate_wait = apply_gate_started.elapsed();
        self.metrics
            .record_commit_apply_gate_wait(ctx.timing.apply_gate_wait);

        let apply_started = std::time::Instant::now();
        let outcomes = if let Some(plan) = ctx.plan {
            // BFG fast path: when the plan is
            // L2P-only (no dedup buckets, no rc-touched shards) and
            // every target L2P shard is in buffered mode, run the L2P
            // apply directly on this thread. This skips
            // `enqueue_lane_plan` (channel sends) +
            // `apply_ops_laned`'s lane recv loops, which together
            // average ~230 us per commit on the seqwrite hot path.
            //
            // The plan is consumed by either branch; we move it
            // accordingly. `plan_is_l2p_direct_eligible` is a
            // borrowing check so we can still use `plan` afterwards.
            if self.commit_direct_apply_enabled
                && Self::plan_is_l2p_direct_eligible(&plan, &ctx.volumes)
            {
                match self.apply_l2p_direct(&ctx.volumes, lsn, ctx.bfg, plan, ctx.ops) {
                    Ok(outcomes) => {
                        ctx.timing.apply = apply_started.elapsed();
                        self.metrics.record_commit_apply(ctx.timing.apply);
                        self.metrics.record_commit_direct_apply(ctx.timing.apply);
                        // Direct-apply bypasses `enqueue_lane_plan` and
                        // `apply_ops_laned`, where the lane path retires
                        // its dispatch reservation
                        // (`complete_retained_dispatch`). Skipping that
                        // call would leave our LSN forever in
                        // `dispatch_state.pending`, blocking every
                        // higher-LSN commit on
                        // `mark_wal_durable_and_wait_for_dispatch`.
                        self.complete_retained_dispatch(lsn);
                        outcomes
                    }
                    Err(err) => {
                        ctx.timing.apply = apply_started.elapsed();
                        self.metrics.record_commit_apply(ctx.timing.apply);
                        self.metrics
                            .record_commit_error(ctx.commit_started.elapsed());
                        self.poison_commit_waiters(&err);
                        return Err(err);
                    }
                }
            } else {
                let enqueue_started = std::time::Instant::now();
                let queued_plan = self.enqueue_lane_plan(
                    &ctx.volumes,
                    lsn,
                    ctx.bfg,
                    plan,
                    Arc::new(ctx.ops.to_vec()),
                );
                ctx.timing.lane_enqueue = enqueue_started.elapsed();
                match self.apply_ops_laned(lsn, ctx.ops.len(), queued_plan) {
                    Ok((outcomes, laned_timing)) => {
                        ctx.timing.apply = apply_started.elapsed();
                        ctx.timing.laned = laned_timing;
                        self.metrics.record_commit_apply(ctx.timing.apply);
                        self.metrics.record_commit_apply_laned(
                            laned_timing.l2p_wait,
                            laned_timing.rc_enqueue,
                            laned_timing.rc_wait,
                            laned_timing.dedup_enqueue,
                            laned_timing.dedup_wait,
                        );
                        outcomes
                    }
                    Err(err) => {
                        ctx.timing.apply = apply_started.elapsed();
                        self.metrics.record_commit_apply(ctx.timing.apply);
                        self.metrics
                            .record_commit_error(ctx.commit_started.elapsed());
                        self.poison_commit_waiters(&err);
                        return Err(err);
                    }
                }
            }
        } else {
            if let Err(err) = self.wait_for_global_apply_turn(lsn) {
                ctx.timing.apply = apply_started.elapsed();
                self.metrics.record_commit_apply(ctx.timing.apply);
                self.metrics
                    .record_commit_error(ctx.commit_started.elapsed());
                return Err(err);
            }
            match self.apply_commit_batch(&ctx.volumes, lsn, ctx.bfg, ctx.ops) {
                Ok(outcomes) => {
                    ctx.timing.apply = apply_started.elapsed();
                    self.metrics.record_commit_apply(ctx.timing.apply);
                    outcomes
                }
                Err(err) => {
                    ctx.timing.apply = apply_started.elapsed();
                    self.metrics.record_commit_apply(ctx.timing.apply);
                    self.metrics
                        .record_commit_error(ctx.commit_started.elapsed());
                    self.poison_commit_waiters(&err);
                    return Err(err);
                }
            }
        };
        if let Err(err) = self.faults.inject(FaultPoint::CommitPostApplyBeforeLsnBump) {
            self.metrics
                .record_commit_error(ctx.commit_started.elapsed());
            self.poison_commit_waiters(&err);
            return Err(err);
        }

        let finish_started = std::time::Instant::now();
        if let Err(err) = self.finish_global_apply(lsn) {
            self.metrics
                .record_commit_error(ctx.commit_started.elapsed());
            return Err(err);
        }
        ctx.timing.finish_global_wait = finish_started.elapsed();
        self.metrics
            .record_commit_finish_global_wait(ctx.timing.finish_global_wait);
        if ctx.serial_apply {
            self.complete_retained_dispatch(lsn);
        }
        drop(active_apply);
        drop(apply_guard);
        self.metrics
            .record_commit_read_held(read_held_started.elapsed());

        let total_elapsed = ctx.commit_started.elapsed();
        if total_elapsed >= std::time::Duration::from_secs(1) {
            let cpu_elapsed = ctx
                .cpu_started
                .and_then(|started| thread_cpu_time().map(|now| now.saturating_sub(started)));
            let pending = self.pending_state();
            let metrics = self.metrics.snapshot();
            tracing::warn!(
                lsn,
                ops = ctx.ops.len(),
                serial_apply = ctx.serial_apply,
                plan_l2p_lanes = ctx.plan_l2p_lanes,
                plan_rc_lanes = ctx.plan_rc_lanes,
                plan_dedup_ops = ctx.plan_dedup_ops,
                dispatch_lanes = ctx.dispatch_lanes,
                total_ms = total_elapsed.as_millis() as u64,
                thread_cpu_ms = cpu_elapsed.map(|d| d.as_millis() as u64),
                drop_gate_wait_us = duration_us(ctx.timing.drop_gate_wait),
                plan_us = duration_us(ctx.timing.plan),
                encode_us = duration_us(ctx.timing.encode),
                wal_submit_us = duration_us(ctx.timing.wal_submit),
                dispatch_wait_us = duration_us(ctx.timing.dispatch_wait),
                apply_gate_wait_us = duration_us(ctx.timing.apply_gate_wait),
                lane_enqueue_us = duration_us(ctx.timing.lane_enqueue),
                apply_us = duration_us(ctx.timing.apply),
                l2p_lane_wait_us = duration_us(ctx.timing.laned.l2p_wait),
                rc_lane_enqueue_us = duration_us(ctx.timing.laned.rc_enqueue),
                rc_lane_wait_us = duration_us(ctx.timing.laned.rc_wait),
                dedup_lane_enqueue_us = duration_us(ctx.timing.laned.dedup_enqueue),
                dedup_lane_wait_us = duration_us(ctx.timing.laned.dedup_wait),
                finish_global_wait_us = duration_us(ctx.timing.finish_global_wait),
                wal_submit_wait_max_us = metrics.wal_submit_wait_max_us,
                wal_write_max_us = metrics.wal_write_max_us,
                wal_fsync_max_us = metrics.wal_fsync_max_us,
                wal_batch_records_max = metrics.wal_batch_records_max,
                pending_dispatch = pending.dispatch_pending,
                pending_dedup_lane_q = pending.dedup_lane_queue,
                pending_l2p_apply_q = pending.l2p_apply_queue,
                pending_l2p_dirty = pending.l2p_pagebuf_dirty,
                pending_rc_apply_q = pending.rc_apply_queue,
                pending_rc_dirty = pending.rc_pagebuf_dirty,
                flush_total_max_us = metrics.flush_total_max_us,
                flush_io_max_us = metrics.flush_io_max_us,
                flush_install_max_us = metrics.flush_install_max_us,
                flush_reclaim_max_us = metrics.flush_reclaim_max_us,
                slow_message
            );
        }
        self.metrics.record_commit_success(total_elapsed);
        Ok((lsn, outcomes))
    }

    fn checkpoint_unlogged_before_wal_commit(&self) -> Result<()> {
        if self.unlogged_pending_lsn.lock().is_none() {
            return Ok(());
        }
        self.flush()?;
        Ok(())
    }

    fn apply_op(
        &self,
        volumes: &HashMap<VolumeOrdinal, Arc<Volume>>,
        lsn: Lsn,
        bfg: crate::types::Bfg,
        op: &WalOp,
    ) -> Result<ApplyOutcome> {
        let snap_lookup = |vol: VolumeOrdinal| -> Vec<SnapInfo> { self.snap_info_for_vol(vol) };
        let op_started = std::time::Instant::now();
        let outcome = apply_op_bare(
            volumes,
            &self.refcount_shards,
            &self.dedup_index,
            &self.page_store,
            lsn,
            bfg,
            op,
            &snap_lookup,
            self.rc_authoritative_reclaim,
        )?;
        record_per_op_apply(&self.metrics, op, op_started.elapsed());
        Ok(outcome)
    }

    /// Append a lifecycle op to the dedicated journal and reserve an
    /// LSN for its apply slot. The journal's per-record fsync is the
    /// durability event; `wal.reserve_unlogged` only bumps the
    /// in-memory LSN counter so apply ordering and `last_applied_lsn`
    /// semantics stay intact.
    ///
    /// The returned seq is published through
    /// `lifecycle_applied_watermark` so the next checkpoint commit
    /// stamps `manifest.lifecycle_replay_seq`.
    ///
    /// Callers must hold `apply_gate.write()` (every existing lifecycle
    /// callsite does) — the watermark bump and the LSN reservation are
    /// not synchronised against concurrent lifecycle submits otherwise.
    ///
    /// Commit a single Lineage-GC `FreePbas` op outside of `commit_ops`.
    ///
    /// FreePbas has no lifecycle-journal entry by design — apply is
    /// idempotent and the walker re-emits any still-dead PBA on the
    /// next GC cycle, so a crash before this LSN gets covered by a
    /// manifest checkpoint is harmless. We allocate an LSN under
    /// `lsn_alloc.reserve` (so dispatch ordering stays intact), wait
    /// for global LSN turn, then apply on the caller thread.
    pub(crate) fn commit_free_pbas(
        &self,
        vol_ord: VolumeOrdinal,
        pbas: &[Pba],
    ) -> Result<ApplyOutcome> {
        // Lock order: drop_gate.read() BEFORE bfg.enter() — matches commit_ops
        // and is load-bearing for deadlock-freedom. A commit parked at
        // drop_gate.read() (behind a lifecycle op's drop_gate.write) must NOT
        // already hold a bfg guard: take_snapshot / create_volume force-sync
        // while holding drop_gate.write, and their roll_to_quiescing waits for
        // slots[cur].inflight == 0. An enter-before-read commit (the
        // LineageGcWorker runs this autonomously) would pin inflight while
        // parked on drop_gate.read → roll never drains → hard deadlock. Entering
        // AFTER drop_gate.read keeps the reserve-after-enter / record_lsn-under-
        // guard sequence below identical to commit_ops.
        let _drop_guard = self.drop_gate.read();
        let _bfg_guard = self.bfg.enter();
        let footprint = DispatchFootprint::global();
        let lsn = self.lsn_alloc.reserve(|lsn| {
            self.register_dispatch_intent(lsn, footprint);
        })?;
        _bfg_guard.record_lsn(lsn);
        self.mark_wal_durable_and_wait_for_dispatch(lsn)?;

        let _apply_guard = self.acquire_commit_apply_gate(lsn);
        let _active = self.enter_active_apply(lsn);
        let outcome = apply_free_pbas(&self.refcount_shards, lsn, _bfg_guard.bfg(), pbas)?;
        self.finish_global_apply(lsn)?;
        self.advance_dispatch_lsn(lsn);
        Ok(outcome)
    }

    pub(super) fn submit_lifecycle_op(
        &self,
        lifecycle_op: &crate::lifecycle_log::LifecycleOp,
    ) -> Result<Lsn> {
        let journal = self.lifecycle_journal.as_ref().ok_or_else(|| {
            MetaDbError::Corruption(
                "submit_lifecycle_op called without an open lifecycle journal".into(),
            )
        })?;
        let body = crate::lifecycle_log::op::encode(lifecycle_op);
        let lsn = self.lsn_alloc.reserve(|_| {})?;
        let seq = journal.lock().append(&body)?;
        self.set_lifecycle_applied_watermark(seq);
        Ok(lsn)
    }

    /// Lifecycle commit variant for callers that hold only
    /// `drop_gate.read()` (PromotionChunk / PromotionComplete) and
    /// therefore race with concurrent `commit_ops` / `commit_free_pbas`.
    /// Unlike `submit_lifecycle_op` (which presumes `apply_gate.write()`
    /// upstream), this registers a Global dispatch footprint so the
    /// scheduler serializes the rc-mutating lifecycle apply against
    /// every other in-flight commit in LSN order. Without this, an
    /// out-of-order apply of a lower-LSN PromotionChunk against a
    /// higher-LSN FreePbas-stamped rc page hit the strict-`>`
    /// replay-skip in `RcShard::stage` and silently dropped the incref
    /// (refcount_drainer concurrent test caught this).
    ///
    /// On return the caller must still acquire `apply_gate.read()`,
    /// run the apply, then call `finish_global_apply` +
    /// `advance_dispatch_lsn` to release the dispatch entry.
    pub(super) fn submit_lifecycle_op_with_dispatch(
        &self,
        lifecycle_op: &crate::lifecycle_log::LifecycleOp,
    ) -> Result<Lsn> {
        let journal = self.lifecycle_journal.as_ref().ok_or_else(|| {
            MetaDbError::Corruption(
                "submit_lifecycle_op_with_dispatch called without an open lifecycle journal".into(),
            )
        })?;
        let body = crate::lifecycle_log::op::encode(lifecycle_op);
        let footprint = DispatchFootprint::global();
        let lsn = self.lsn_alloc.reserve(|lsn| {
            self.register_dispatch_intent(lsn, footprint);
        })?;
        match journal.lock().append(&body) {
            Ok(seq) => {
                self.set_lifecycle_applied_watermark(seq);
            }
            Err(err) => {
                self.forget_dispatch_intent(lsn);
                return Err(err);
            }
        }
        self.mark_wal_durable_and_wait_for_dispatch(lsn)?;
        Ok(lsn)
    }

    /// Apply a commit batch under `apply_gate.read()`. Large batches
    /// group ops by shard so each shard lock is taken once per (vol,
    /// shard) rather than once per op. Small batches fall through to
    /// the serial path — the bucketing overhead dominates below a
    /// handful of ops.
    ///
    /// Correctness:
    /// - Intra-bucket order is preserved (`Vec<usize>` of original op
    ///   indices), so multiple ops to the same (vol, lba) or same pba
    ///   apply in caller order.
    /// - Cross-bucket order is relaxed: L2P shards and refcount shards
    ///   live on disjoint trees, and same-LSN `cow_for_write` is
    ///   idempotent via `page.generation >= lsn`, so reordering between
    ///   two shards does not change the committed state.
    /// - Each shard lock is held for the span of its bucket only;
    ///   locks are taken one at a time in (vol_ord, shard_id) sorted
    ///   order, so the CLAUDE-documented "cross-shard ops take locks
    ///   in shard index order" invariant still holds.
    ///
    /// Defensive fallback: if the batch contains a lifecycle op
    /// (DropSnapshot, CreateVolume, DropVolume, CloneVolume), a guarded
    /// remap, or a remap against a volume with live snapshots, we fall
    /// back to serial apply. Lifecycle ops do not currently reach
    /// `commit_ops` from any caller — they have their own entry points
    /// with stronger locking — but the fallback keeps the bucketed path
    /// safe if a future caller routes them through here.
    fn apply_commit_batch(
        &self,
        volumes: &HashMap<VolumeOrdinal, Arc<Volume>>,
        lsn: Lsn,
        bfg: crate::types::Bfg,
        ops: &[WalOp],
    ) -> Result<Vec<ApplyOutcome>> {
        const BUCKET_THRESHOLD: usize = 8;
        if ops.len() < BUCKET_THRESHOLD || self.batch_requires_serial_apply(ops) {
            let mut outcomes = Vec::with_capacity(ops.len());
            for op in ops {
                outcomes.push(self.apply_op(volumes, lsn, bfg, op)?);
            }
            return Ok(outcomes);
        }
        self.apply_ops_grouped(volumes, lsn, bfg, ops)
    }

    fn batch_requires_serial_apply(&self, ops: &[WalOp]) -> bool {
        if batch_contains_lifecycle_op(ops) {
            return true;
        }

        // Guarded remaps used to fall back to serial apply because the
        // lane path's `apply_l2p_bucket` did not honour the guard. The
        // bucket now does the rc check inline (same lock order as the
        // serial path: L2P shard write → refcount shard lock), so guard
        // alone no longer forces serial. Snapshot-bearing volumes still
        // need the serial path for the snap-pin walk inside
        // `apply_l2p_remap` / `apply_l2p_remap_range` — the lane
        // path's leaf-run primitives do not consult `snap_infos`.
        let mut remap_vols = HashSet::new();
        for op in ops {
            match op {
                WalOp::L2pRemap { vol_ord, .. } | WalOp::L2pRemapRange { vol_ord, .. } => {
                    remap_vols.insert(*vol_ord);
                }
                _ => {}
            }
        }

        remap_vols
            .into_iter()
            .any(|vol_ord| !self.snap_info_for_vol(vol_ord).is_empty())
    }

    fn batch_uses_serial_apply(&self, ops: &[WalOp]) -> bool {
        // B2: laned `apply_l2p_bucket` is buffer-aware (see
        // `apply_l2p_bucket_buffer`); the buffer path no longer forces
        // serial. Snapshot-bearing volumes still need serial via the
        // unchanged `batch_requires_serial_apply` rule (snap-pin walk
        // lives in `apply_l2p_remap`).
        self.batch_requires_serial_apply(ops)
    }

    pub(super) fn poison_commit_waiters(&self, err: &MetaDbError) {
        let mut poison = self.commit_poison.lock();
        if poison.is_none() {
            *poison = Some(err.to_string());
        }
        self.dispatch_cvar.notify_all();
        self.commit_cvar.notify_all();
    }

    fn commit_poison_error(&self) -> Option<MetaDbError> {
        self.commit_poison
            .lock()
            .as_ref()
            .map(|msg| MetaDbError::Corruption(format!("commit pipeline failed: {msg}")))
    }

    /// Poison the forced-sync subsystem after a non-recoverable sync-cycle
    /// failure (e.g. a faulted manifest fsync that left a BFG slot stuck in
    /// Syncing). Set-once (first writer wins), then abort the BFG state machine
    /// so every parked waiter (`promote_to_syncing`, `wait_until_synced`,
    /// `roll_to_quiescing`) unblocks instead of hanging, and fail every
    /// still-queued snapshot task so none can land durable after its
    /// `take_snapshot` caller was told the subsystem failed. Recovery = process
    /// restart (a failed inline sync may have left deferred RC apply state
    /// un-retryable; we deliberately do NOT retry). Called from BOTH the
    /// threads-off `flush_with_gate` Err arm and the threads-on `sync_work`
    /// closure.
    ///
    /// Lock order: the `sync_poison` lock is released (scoped block) BEFORE
    /// `bfg.mark_aborted()` (which locks `bfg.inner`) and the
    /// `pending_sync_tasks` lock, so no new `sync_poison`↔`bfg.inner` /
    /// `pending_sync_tasks` ordering edge is introduced.
    pub(crate) fn poison_sync(&self, err: &MetaDbError) {
        {
            let mut p = self.sync_poison.lock();
            if p.is_none() {
                *p = Some(err.to_string());
            }
        }
        self.bfg.mark_aborted();
        let mut tasks = self.pending_sync_tasks.lock();
        for task in tasks.drain(..) {
            *task.result.lock() = Some(Err(MetaDbError::Corruption(
                "metadb persistence subsystem failed; restart required (sync aborted)".into(),
            )));
        }
    }

    pub(crate) fn sync_poison_error(&self) -> Option<MetaDbError> {
        self.sync_poison.lock().as_ref().map(|msg| {
            MetaDbError::Corruption(format!(
                "metadb persistence subsystem failed; restart required: {msg}"
            ))
        })
    }

    pub(super) fn register_dispatch_intent(&self, lsn: Lsn, footprint: DispatchFootprint) {
        let mut state = self.dispatch_state.lock();
        let old = state.pending.insert(
            lsn,
            DispatchEntry {
                footprint,
                durable: false,
            },
        );
        debug_assert!(
            old.is_none(),
            "duplicate dispatch reservation for LSN {lsn}"
        );
        self.dispatch_cvar.notify_all();
    }

    pub(super) fn mark_wal_durable_and_wait_for_dispatch(&self, lsn: Lsn) -> Result<()> {
        let mut state = self.dispatch_state.lock();
        let entry = state.pending.get_mut(&lsn).ok_or_else(|| {
            MetaDbError::Corruption(format!("missing dispatch reservation for LSN {lsn}"))
        })?;
        entry.durable = true;
        self.dispatch_cvar.notify_all();

        loop {
            if let Some(err) = self.commit_poison_error() {
                return Err(err);
            }
            if dispatch_ready(&state, lsn) {
                return Ok(());
            }
            self.dispatch_cvar.wait(&mut state);
        }
    }

    pub(super) fn forget_dispatch_intent(&self, lsn: Lsn) {
        let mut state = self.dispatch_state.lock();
        state.pending.remove(&lsn);
        self.dispatch_cvar.notify_all();
    }

    fn complete_retained_dispatch(&self, lsn: Lsn) {
        self.forget_dispatch_intent(lsn);
    }

    pub(super) fn advance_dispatch_lsn(&self, lsn: Lsn) {
        // Lifecycle paths still call this at the old "dispatch complete"
        // point. They hold `drop_gate.write()` and `apply_gate.write()`,
        // so ordinary commits cannot have in-flight dispatch reservations
        // that need ordering against them.
        self.forget_dispatch_intent(lsn);
    }

    pub(super) fn wait_for_global_apply_turn(&self, lsn: Lsn) -> Result<()> {
        let mut applied = self.last_applied_lsn.lock();
        while *applied + 1 < lsn {
            if let Some(err) = self.commit_poison_error() {
                return Err(err);
            }
            self.commit_cvar.wait(&mut applied);
        }
        Ok(())
    }

    /// Mark `lsn` as applied (lane work + apply_gate already done) and
    /// advance the watermark `last_applied_lsn` if `lsn` extends the
    /// contiguous prefix of completed LSNs.
    ///
    /// Pre-redesign this was a strict-LSN-order chain: every commit
    /// parked on `commit_cvar` waiting for `last_applied_lsn + 1 == lsn`,
    /// then bumped + `notify_all`'d. With 128 concurrent in-flight
    /// commits that produced 128 sequential cvar handoffs per LSN burst.
    ///
    /// The new design decouples apply order from LSN order at the
    /// global level: per-lane order is still enforced by the dispatch
    /// footprint protocol (`mark_wal_durable_and_wait_for_dispatch`
    /// only releases a commit when all conflicting lower LSNs have
    /// dispatched), so commits with disjoint footprints can apply in
    /// any order. The watermark catches up via contiguous-prefix pop.
    ///
    /// `wait_for_global_apply_turn` is retained unchanged for lifecycle
    /// ops and serial-apply commits that genuinely need to wait for
    /// `last_applied_lsn >= lsn - 1`; this path still uses
    /// `commit_cvar`. The notify here only fires when the watermark
    /// actually advances, so out-of-order finishes don't broadcast.
    pub(super) fn finish_global_apply(&self, lsn: Lsn) -> Result<()> {
        let advanced_to = {
            let mut applied = self.last_applied_lsn.lock();
            let mut set = self.applied_set.lock();
            debug_assert!(
                lsn > *applied,
                "finish_global_apply called with LSN {lsn} <= already-applied watermark {}",
                *applied
            );
            set.insert(lsn);
            let before = *applied;
            // Pop contiguous prefix off the head of the set. Each
            // pop bumps the watermark by 1; the loop runs zero times
            // if our LSN didn't complete the next contiguous slot,
            // and runs N times if we filled a gap that retired N
            // already-applied LSNs into the watermark.
            while set.remove(&(*applied + 1)) {
                *applied += 1;
            }
            if *applied != before {
                Some(*applied)
            } else {
                None
            }
        };
        // Only notify on actual watermark advances. Lifecycle ops and
        // serial-apply commits waiting on `commit_cvar` care about the
        // watermark; out-of-order laned finishes that don't move it
        // don't need to wake anyone.
        if let Some(applied) = advanced_to {
            self.last_applied_lsn_observed
                .store(applied, std::sync::atomic::Ordering::Relaxed);
            self.commit_cvar.notify_all();
        }
        Ok(())
    }
}

fn replay_batch_requires_serial_apply(
    ops: &[WalOp],
    snap_info_for_vol: &dyn Fn(VolumeOrdinal) -> Vec<SnapInfo>,
) -> bool {
    if batch_contains_lifecycle_op(ops) {
        return true;
    }

    let mut remap_vols = HashSet::new();
    for op in ops {
        match op {
            WalOp::L2pRemap { vol_ord, .. } | WalOp::L2pRemapRange { vol_ord, .. } => {
                remap_vols.insert(*vol_ord);
            }
            _ => {}
        }
    }
    remap_vols
        .into_iter()
        .any(|vol_ord| !snap_info_for_vol(vol_ord).is_empty())
}

/// Record per-op-type apply latency for the serial fallback path.
/// Lifecycle ops (DropSnapshot / CreateVolume / DropVolume / CloneVolume) are
/// rare and self-instrument elsewhere, so they're skipped here.
fn record_per_op_apply(metrics: &MetaMetrics, op: &WalOp, elapsed: std::time::Duration) {
    match op {
        WalOp::L2pPut { .. } => metrics.record_apply_l2p_put(elapsed),
        WalOp::L2pDelete { .. } => metrics.record_apply_l2p_delete(elapsed),
        WalOp::L2pRemap { .. } => metrics.record_apply_l2p_remap(elapsed),
        WalOp::L2pRemapRange { values, .. } => {
            metrics.record_apply_l2p_remap_range(values.len() as u64, elapsed)
        }
        WalOp::DedupPut { .. }
        | WalOp::DedupPutGuarded { .. }
        | WalOp::DedupDelete { .. }
        | WalOp::DedupCompareDelete { .. }
        | WalOp::DedupComparePut { .. } => metrics.record_apply_dedup(elapsed),
    }
}

#[cfg(test)]
mod tests;
