use super::super::*;

impl MetaMetrics {
    pub fn snapshot(&self) -> MetaMetricsSnapshot {
        MetaMetricsSnapshot {
            rc_checkpoint_mode: load(&self.rc_checkpoint_mode),
            commit_attempts: load(&self.commit_attempts),
            commit_success: load(&self.commit_success),
            commit_errors: load(&self.commit_errors),
            commit_empty: load(&self.commit_empty),
            commit_ops: load(&self.commit_ops),
            commit_ops_per_tx_max: load(&self.commit_ops_per_tx_max),
            commit_wal_body_bytes: load(&self.commit_wal_body_bytes),
            commit_wal_body_bytes_max: load(&self.commit_wal_body_bytes_max),
            commit_total_us: load(&self.commit_total_us),
            commit_total_max_us: load(&self.commit_total_max_us),
            commit_wal_submit_us: load(&self.commit_wal_submit_us),
            commit_wal_submit_max_us: load(&self.commit_wal_submit_max_us),
            commit_drop_gate_wait_us: load(&self.commit_drop_gate_wait_us),
            commit_drop_gate_wait_max_us: load(&self.commit_drop_gate_wait_max_us),
            commit_apply_wait_us: load(&self.commit_apply_wait_us),
            commit_apply_wait_max_us: load(&self.commit_apply_wait_max_us),
            commit_apply_gate_wait_us: load(&self.commit_apply_gate_wait_us),
            commit_apply_gate_wait_max_us: load(&self.commit_apply_gate_wait_max_us),
            commit_finish_global_wait_us: load(&self.commit_finish_global_wait_us),
            commit_finish_global_wait_max_us: load(&self.commit_finish_global_wait_max_us),
            commit_apply_us: load(&self.commit_apply_us),
            commit_apply_max_us: load(&self.commit_apply_max_us),
            commit_direct_apply_count: load(&self.commit_direct_apply_count),
            commit_direct_apply_us: load(&self.commit_direct_apply_us),
            commit_direct_apply_max_us: load(&self.commit_direct_apply_max_us),
            commit_apply_l2p_wait_us: load(&self.commit_apply_l2p_wait_us),
            commit_apply_l2p_wait_max_us: load(&self.commit_apply_l2p_wait_max_us),
            commit_apply_rc_enqueue_us: load(&self.commit_apply_rc_enqueue_us),
            commit_apply_rc_enqueue_max_us: load(&self.commit_apply_rc_enqueue_max_us),
            commit_apply_rc_wait_us: load(&self.commit_apply_rc_wait_us),
            commit_apply_rc_wait_max_us: load(&self.commit_apply_rc_wait_max_us),
            commit_apply_dedup_enqueue_us: load(&self.commit_apply_dedup_enqueue_us),
            commit_apply_dedup_enqueue_max_us: load(&self.commit_apply_dedup_enqueue_max_us),
            commit_apply_dedup_wait_us: load(&self.commit_apply_dedup_wait_us),
            commit_apply_dedup_wait_max_us: load(&self.commit_apply_dedup_wait_max_us),
            commit_plan_us: load(&self.commit_plan_us),
            commit_plan_max_us: load(&self.commit_plan_max_us),
            commit_encode_us: load(&self.commit_encode_us),
            commit_encode_max_us: load(&self.commit_encode_max_us),
            commit_unlogged_gate_wait_us: load(&self.commit_unlogged_gate_wait_us),
            commit_unlogged_gate_wait_max_us: load(&self.commit_unlogged_gate_wait_max_us),
            commit_checkpoint_unlogged_us: load(&self.commit_checkpoint_unlogged_us),
            commit_checkpoint_unlogged_max_us: load(&self.commit_checkpoint_unlogged_max_us),
            commit_read_held_us: load(&self.commit_read_held_us),
            commit_read_held_max_us: load(&self.commit_read_held_max_us),
            wal_submit_calls: load(&self.wal_submit_calls),
            wal_submit_wait_us: load(&self.wal_submit_wait_us),
            wal_submit_wait_max_us: load(&self.wal_submit_wait_max_us),
            wal_queue_wait_us: load(&self.wal_queue_wait_us),
            wal_queue_wait_max_us: load(&self.wal_queue_wait_max_us),
            wal_writer_busy_us: load(&self.wal_writer_busy_us),
            wal_writer_busy_max_us: load(&self.wal_writer_busy_max_us),
            wal_wake_roundtrip_us: load(&self.wal_wake_roundtrip_us),
            wal_wake_roundtrip_max_us: load(&self.wal_wake_roundtrip_max_us),
            wal_batches: load(&self.wal_batches),
            wal_records: load(&self.wal_records),
            wal_bytes: load(&self.wal_bytes),
            wal_rotates: load(&self.wal_rotates),
            wal_write_us: load(&self.wal_write_us),
            wal_write_max_us: load(&self.wal_write_max_us),
            wal_fsyncs: load(&self.wal_fsyncs),
            wal_fsync_us: load(&self.wal_fsync_us),
            wal_fsync_max_us: load(&self.wal_fsync_max_us),
            wal_batch_records_max: load(&self.wal_batch_records_max),
            wal_batch_bytes_max: load(&self.wal_batch_bytes_max),
            wal_async_acks_total: load(&self.wal_async_acks_total),
            wal_async_pending_bytes_total: load(&self.wal_async_pending_bytes_total),
            wal_fsync_at_bfg_sync_us: load(&self.wal_fsync_at_bfg_sync_us),
            wal_fsync_at_bfg_sync_max_us: load(&self.wal_fsync_at_bfg_sync_max_us),
            range_delete_calls: load(&self.range_delete_calls),
            range_delete_success: load(&self.range_delete_success),
            range_delete_errors: load(&self.range_delete_errors),
            range_delete_noop: load(&self.range_delete_noop),
            range_delete_captured_entries: load(&self.range_delete_captured_entries),
            range_delete_chunks: load(&self.range_delete_chunks),
            range_delete_total_us: load(&self.range_delete_total_us),
            range_delete_total_max_us: load(&self.range_delete_total_max_us),
            range_delete_scan_us: load(&self.range_delete_scan_us),
            range_delete_scan_max_us: load(&self.range_delete_scan_max_us),
            range_delete_wal_us: load(&self.range_delete_wal_us),
            range_delete_wal_max_us: load(&self.range_delete_wal_max_us),
            range_delete_apply_wait_us: load(&self.range_delete_apply_wait_us),
            range_delete_apply_wait_max_us: load(&self.range_delete_apply_wait_max_us),
            range_delete_apply_us: load(&self.range_delete_apply_us),
            range_delete_apply_max_us: load(&self.range_delete_apply_max_us),
            range_delete_drop_gate_wait_us: load(&self.range_delete_drop_gate_wait_us),
            range_delete_drop_gate_wait_max_us: load(&self.range_delete_drop_gate_wait_max_us),
            range_delete_apply_gate_wait_us: load(&self.range_delete_apply_gate_wait_us),
            range_delete_apply_gate_wait_max_us: load(&self.range_delete_apply_gate_wait_max_us),
            cleanup_calls: load(&self.cleanup_calls),
            cleanup_success: load(&self.cleanup_success),
            cleanup_errors: load(&self.cleanup_errors),
            cleanup_noop: load(&self.cleanup_noop),
            cleanup_pbas: load(&self.cleanup_pbas),
            cleanup_hashes_found: load(&self.cleanup_hashes_found),
            cleanup_forward_checks: load(&self.cleanup_forward_checks),
            cleanup_tombstones_emitted: load(&self.cleanup_tombstones_emitted),
            cleanup_tx_ops: load(&self.cleanup_tx_ops),
            cleanup_total_us: load(&self.cleanup_total_us),
            cleanup_total_max_us: load(&self.cleanup_total_max_us),
            cleanup_scan_us: load(&self.cleanup_scan_us),
            cleanup_scan_max_us: load(&self.cleanup_scan_max_us),
            cleanup_forward_check_us: load(&self.cleanup_forward_check_us),
            cleanup_forward_check_max_us: load(&self.cleanup_forward_check_max_us),
            cleanup_commit_us: load(&self.cleanup_commit_us),
            cleanup_commit_max_us: load(&self.cleanup_commit_max_us),
            apply_l2p_put_count: load(&self.apply_l2p_put_count),
            apply_l2p_put_us: load(&self.apply_l2p_put_us),
            apply_l2p_put_max_us: load(&self.apply_l2p_put_max_us),
            apply_l2p_delete_count: load(&self.apply_l2p_delete_count),
            apply_l2p_delete_us: load(&self.apply_l2p_delete_us),
            apply_l2p_delete_max_us: load(&self.apply_l2p_delete_max_us),
            apply_l2p_remap_count: load(&self.apply_l2p_remap_count),
            apply_l2p_remap_us: load(&self.apply_l2p_remap_us),
            apply_l2p_remap_max_us: load(&self.apply_l2p_remap_max_us),
            apply_l2p_remap_range_count: load(&self.apply_l2p_remap_range_count),
            apply_l2p_remap_range_lbas: load(&self.apply_l2p_remap_range_lbas),
            apply_l2p_remap_range_us: load(&self.apply_l2p_remap_range_us),
            apply_l2p_remap_range_max_us: load(&self.apply_l2p_remap_range_max_us),
            apply_l2p_range_delete_count: load(&self.apply_l2p_range_delete_count),
            apply_l2p_range_delete_us: load(&self.apply_l2p_range_delete_us),
            apply_l2p_range_delete_max_us: load(&self.apply_l2p_range_delete_max_us),
            apply_l2p_bucket_count: load(&self.apply_l2p_bucket_count),
            apply_l2p_bucket_ops: load(&self.apply_l2p_bucket_ops),
            apply_l2p_bucket_total_us: load(&self.apply_l2p_bucket_total_us),
            apply_l2p_bucket_total_max_us: load(&self.apply_l2p_bucket_total_max_us),
            apply_l2p_bucket_tree_lock_wait_us: load(&self.apply_l2p_bucket_tree_lock_wait_us),
            apply_l2p_bucket_tree_lock_wait_max_us: load(
                &self.apply_l2p_bucket_tree_lock_wait_max_us,
            ),
            apply_l2p_bucket_read_view_prepare_us: load(
                &self.apply_l2p_bucket_read_view_prepare_us,
            ),
            apply_l2p_bucket_read_view_prepare_max_us: load(
                &self.apply_l2p_bucket_read_view_prepare_max_us,
            ),
            apply_l2p_bucket_ops_us: load(&self.apply_l2p_bucket_ops_us),
            apply_l2p_bucket_ops_max_us: load(&self.apply_l2p_bucket_ops_max_us),
            apply_l2p_bucket_finish_us: load(&self.apply_l2p_bucket_finish_us),
            apply_l2p_bucket_finish_max_us: load(&self.apply_l2p_bucket_finish_max_us),
            apply_l2p_bucket_publish_us: load(&self.apply_l2p_bucket_publish_us),
            apply_l2p_bucket_publish_max_us: load(&self.apply_l2p_bucket_publish_max_us),
            apply_refcount_count: load(&self.apply_refcount_count),
            apply_refcount_us: load(&self.apply_refcount_us),
            apply_refcount_max_us: load(&self.apply_refcount_max_us),
            apply_refcount_batch_count: load(&self.apply_refcount_batch_count),
            apply_refcount_batch_actions: load(&self.apply_refcount_batch_actions),
            apply_refcount_batch_pbas: load(&self.apply_refcount_batch_pbas),
            apply_refcount_breakdown_sampled_pbas: load(
                &self.apply_refcount_breakdown_sampled_pbas,
            ),
            apply_refcount_pba_grouping_us: load(&self.apply_refcount_pba_grouping_us),
            apply_refcount_pba_grouping_max_us: load(&self.apply_refcount_pba_grouping_max_us),
            apply_refcount_base_page_lookup_us: load(&self.apply_refcount_base_page_lookup_us),
            apply_refcount_base_page_lookup_max_us: load(
                &self.apply_refcount_base_page_lookup_max_us,
            ),
            apply_refcount_base_lookup_attempts: load(&self.apply_refcount_base_lookup_attempts),
            apply_refcount_epoch_retries: load(&self.apply_refcount_epoch_retries),
            apply_refcount_fold_lock_wait_us: load(&self.apply_refcount_fold_lock_wait_us),
            apply_refcount_fold_lock_wait_max_us: load(&self.apply_refcount_fold_lock_wait_max_us),
            apply_refcount_slot_lock_wait_us: load(&self.apply_refcount_slot_lock_wait_us),
            apply_refcount_slot_lock_wait_max_us: load(&self.apply_refcount_slot_lock_wait_max_us),
            apply_refcount_pending_slot_scan_us: load(&self.apply_refcount_pending_slot_scan_us),
            apply_refcount_pending_slot_scan_max_us: load(
                &self.apply_refcount_pending_slot_scan_max_us,
            ),
            apply_refcount_delta_merge_us: load(&self.apply_refcount_delta_merge_us),
            apply_refcount_delta_merge_max_us: load(&self.apply_refcount_delta_merge_max_us),
            apply_dedup_count: load(&self.apply_dedup_count),
            apply_dedup_us: load(&self.apply_dedup_us),
            apply_dedup_max_us: load(&self.apply_dedup_max_us),
            dedup_lane_tasks: load(&self.dedup_lane_tasks),
            dedup_lane_ops: load(&self.dedup_lane_ops),
            dedup_lane_ready_queue_wait_us: load(&self.dedup_lane_ready_queue_wait_us),
            dedup_lane_ready_queue_wait_max_us: load(&self.dedup_lane_ready_queue_wait_max_us),
            dedup_lane_exec_us: load(&self.dedup_lane_exec_us),
            dedup_lane_exec_max_us: load(&self.dedup_lane_exec_max_us),
            dedup_lane_idle_us: load(&self.dedup_lane_idle_us),
            dedup_lane_idle_max_us: load(&self.dedup_lane_idle_max_us),
            dedup_lane_wakeups: load(&self.dedup_lane_wakeups),
            dedup_lane_empty_wakeups: load(&self.dedup_lane_empty_wakeups),
            dedup_lane_burst_total: load(&self.dedup_lane_burst_total),
            dedup_lane_burst_max: load(&self.dedup_lane_burst_max),
            dedup_lane_queue_depth_max: load(&self.dedup_lane_queue_depth_max),
            l2p_apply_lane_tasks: load(&self.l2p_apply_lane_tasks),
            l2p_apply_lane_queue_depth_max: load(&self.l2p_apply_lane_queue_depth_max),
            l2p_apply_lane_queue_wait_us: load(&self.l2p_apply_lane_queue_wait_us),
            l2p_apply_lane_queue_wait_max_us: load(&self.l2p_apply_lane_queue_wait_max_us),
            l2p_apply_lane_exec_us: load(&self.l2p_apply_lane_exec_us),
            l2p_apply_lane_exec_max_us: load(&self.l2p_apply_lane_exec_max_us),
            l2p_apply_lane_idle_us: load(&self.l2p_apply_lane_idle_us),
            l2p_apply_lane_idle_max_us: load(&self.l2p_apply_lane_idle_max_us),
            l2p_apply_lane_wakeups: load(&self.l2p_apply_lane_wakeups),
            l2p_apply_lane_empty_wakeups: load(&self.l2p_apply_lane_empty_wakeups),
            l2p_apply_lane_burst_total: load(&self.l2p_apply_lane_burst_total),
            l2p_apply_lane_burst_max: load(&self.l2p_apply_lane_burst_max),
            rc_apply_lane_tasks: load(&self.rc_apply_lane_tasks),
            rc_apply_lane_queue_depth_max: load(&self.rc_apply_lane_queue_depth_max),
            rc_apply_lane_queue_wait_us: load(&self.rc_apply_lane_queue_wait_us),
            rc_apply_lane_queue_wait_max_us: load(&self.rc_apply_lane_queue_wait_max_us),
            rc_apply_lane_exec_us: load(&self.rc_apply_lane_exec_us),
            rc_apply_lane_exec_max_us: load(&self.rc_apply_lane_exec_max_us),
            rc_apply_lane_idle_us: load(&self.rc_apply_lane_idle_us),
            rc_apply_lane_idle_max_us: load(&self.rc_apply_lane_idle_max_us),
            rc_apply_lane_pending_set_wait_us: load(&self.rc_apply_lane_pending_set_wait_us),
            rc_apply_lane_pending_set_wait_max_us: load(
                &self.rc_apply_lane_pending_set_wait_max_us,
            ),
            rc_apply_lane_wakeups: load(&self.rc_apply_lane_wakeups),
            rc_apply_lane_empty_wakeups: load(&self.rc_apply_lane_empty_wakeups),
            rc_apply_lane_burst_total: load(&self.rc_apply_lane_burst_total),
            rc_apply_lane_burst_max: load(&self.rc_apply_lane_burst_max),
            l2p_apply_lane_shard_tasks: load_shards(&self.l2p_apply_lane_shard_tasks),
            l2p_apply_lane_shard_queue_depth_max: load_shards(
                &self.l2p_apply_lane_shard_queue_depth_max,
            ),
            l2p_apply_lane_shard_queue_wait_us: load_shards(
                &self.l2p_apply_lane_shard_queue_wait_us,
            ),
            l2p_apply_lane_shard_queue_wait_max_us: load_shards(
                &self.l2p_apply_lane_shard_queue_wait_max_us,
            ),
            l2p_apply_lane_shard_exec_us: load_shards(&self.l2p_apply_lane_shard_exec_us),
            l2p_apply_lane_shard_exec_max_us: load_shards(&self.l2p_apply_lane_shard_exec_max_us),
            l2p_apply_lane_shard_idle_us: load_shards(&self.l2p_apply_lane_shard_idle_us),
            l2p_apply_lane_shard_wakeups: load_shards(&self.l2p_apply_lane_shard_wakeups),
            l2p_apply_lane_shard_empty_wakeups: load_shards(
                &self.l2p_apply_lane_shard_empty_wakeups,
            ),
            l2p_apply_lane_shard_burst_total: load_shards(&self.l2p_apply_lane_shard_burst_total),
            l2p_apply_lane_shard_burst_max: load_shards(&self.l2p_apply_lane_shard_burst_max),
            rc_apply_lane_shard_tasks: load_shards(&self.rc_apply_lane_shard_tasks),
            rc_apply_lane_shard_queue_depth_max: load_shards(
                &self.rc_apply_lane_shard_queue_depth_max,
            ),
            rc_apply_lane_shard_queue_wait_us: load_shards(&self.rc_apply_lane_shard_queue_wait_us),
            rc_apply_lane_shard_queue_wait_max_us: load_shards(
                &self.rc_apply_lane_shard_queue_wait_max_us,
            ),
            rc_apply_lane_shard_exec_us: load_shards(&self.rc_apply_lane_shard_exec_us),
            rc_apply_lane_shard_exec_max_us: load_shards(&self.rc_apply_lane_shard_exec_max_us),
            rc_apply_lane_shard_idle_us: load_shards(&self.rc_apply_lane_shard_idle_us),
            rc_apply_lane_shard_pending_set_wait_us: load_shards(
                &self.rc_apply_lane_shard_pending_set_wait_us,
            ),
            rc_apply_lane_shard_pending_set_wait_max_us: load_shards(
                &self.rc_apply_lane_shard_pending_set_wait_max_us,
            ),
            rc_apply_lane_shard_wakeups: load_shards(&self.rc_apply_lane_shard_wakeups),
            rc_apply_lane_shard_empty_wakeups: load_shards(&self.rc_apply_lane_shard_empty_wakeups),
            rc_apply_lane_shard_burst_total: load_shards(&self.rc_apply_lane_shard_burst_total),
            rc_apply_lane_shard_burst_max: load_shards(&self.rc_apply_lane_shard_burst_max),
            dedup_apply_guard_count: load(&self.dedup_apply_guard_count),
            dedup_apply_guard_us: load(&self.dedup_apply_guard_us),
            dedup_apply_guard_max_us: load(&self.dedup_apply_guard_max_us),
            dedup_apply_forward_put_count: load(&self.dedup_apply_forward_put_count),
            dedup_apply_forward_put_us: load(&self.dedup_apply_forward_put_us),
            dedup_apply_forward_put_max_us: load(&self.dedup_apply_forward_put_max_us),
            dedup_promote_dropped_saturated: load(&self.dedup_promote_dropped_saturated),
            dedup_apply_forward_delete_count: load(&self.dedup_apply_forward_delete_count),
            dedup_apply_forward_delete_us: load(&self.dedup_apply_forward_delete_us),
            dedup_apply_forward_delete_max_us: load(&self.dedup_apply_forward_delete_max_us),
            dedup_apply_reverse_put_count: load(&self.dedup_apply_reverse_put_count),
            dedup_apply_reverse_put_us: load(&self.dedup_apply_reverse_put_us),
            dedup_apply_reverse_put_max_us: load(&self.dedup_apply_reverse_put_max_us),
            dedup_apply_reverse_delete_count: load(&self.dedup_apply_reverse_delete_count),
            dedup_apply_reverse_delete_us: load(&self.dedup_apply_reverse_delete_us),
            dedup_apply_reverse_delete_max_us: load(&self.dedup_apply_reverse_delete_max_us),
            dedup_put_l0_insert_us: load(&self.dedup_put_l0_insert_us),
            dedup_put_l0_insert_max_us: load(&self.dedup_put_l0_insert_max_us),
            dedup_put_l1_put_us: load(&self.dedup_put_l1_put_us),
            dedup_put_l1_put_max_us: load(&self.dedup_put_l1_put_max_us),
            dedup_put_cuckoo_update_existing_us: load(&self.dedup_put_cuckoo_update_existing_us),
            dedup_put_cuckoo_update_existing_max_us: load(
                &self.dedup_put_cuckoo_update_existing_max_us,
            ),
            dedup_put_cuckoo_free_slots_us: load(&self.dedup_put_cuckoo_free_slots_us),
            dedup_put_cuckoo_free_slots_max_us: load(&self.dedup_put_cuckoo_free_slots_max_us),
            dedup_put_cuckoo_try_insert_empty_us: load(&self.dedup_put_cuckoo_try_insert_empty_us),
            dedup_put_cuckoo_try_insert_empty_max_us: load(
                &self.dedup_put_cuckoo_try_insert_empty_max_us,
            ),
            dedup_put_cuckoo_evict_and_insert_us: load(&self.dedup_put_cuckoo_evict_and_insert_us),
            dedup_put_cuckoo_evict_and_insert_max_us: load(
                &self.dedup_put_cuckoo_evict_and_insert_max_us,
            ),
            dedup_put_cuckoo_page_read_cache_wait_us: load(
                &self.dedup_put_cuckoo_page_read_cache_wait_us,
            ),
            dedup_put_cuckoo_page_read_cache_wait_max_us: load(
                &self.dedup_put_cuckoo_page_read_cache_wait_max_us,
            ),
            dedup_put_cuckoo_page_alloc_us: load(&self.dedup_put_cuckoo_page_alloc_us),
            dedup_put_cuckoo_page_alloc_max_us: load(&self.dedup_put_cuckoo_page_alloc_max_us),
            dedup_put_cuckoo_page_write_publish_us: load(
                &self.dedup_put_cuckoo_page_write_publish_us,
            ),
            dedup_put_cuckoo_page_write_publish_max_us: load(
                &self.dedup_put_cuckoo_page_write_publish_max_us,
            ),
            dedup_put_cuckoo_bucket_lock_wait_us: load(&self.dedup_put_cuckoo_bucket_lock_wait_us),
            dedup_put_cuckoo_bucket_lock_wait_max_us: load(
                &self.dedup_put_cuckoo_bucket_lock_wait_max_us,
            ),
            l2p_get_calls: load(&self.l2p_get_calls),
            l2p_get_lock_wait_us: load(&self.l2p_get_lock_wait_us),
            l2p_get_lock_wait_max_us: load(&self.l2p_get_lock_wait_max_us),
            l2p_get_tree_walk_us: load(&self.l2p_get_tree_walk_us),
            l2p_get_tree_walk_max_us: load(&self.l2p_get_tree_walk_max_us),
            l2p_multi_get_calls: load(&self.l2p_multi_get_calls),
            l2p_multi_get_lbas: load(&self.l2p_multi_get_lbas),
            l2p_multi_get_pin_us: load(&self.l2p_multi_get_pin_us),
            l2p_multi_get_pin_max_us: load(&self.l2p_multi_get_pin_max_us),
            l2p_multi_get_volume_us: load(&self.l2p_multi_get_volume_us),
            l2p_multi_get_volume_max_us: load(&self.l2p_multi_get_volume_max_us),
            l2p_multi_get_sort_us: load(&self.l2p_multi_get_sort_us),
            l2p_multi_get_sort_max_us: load(&self.l2p_multi_get_sort_max_us),
            l2p_multi_get_view_us: load(&self.l2p_multi_get_view_us),
            l2p_multi_get_view_max_us: load(&self.l2p_multi_get_view_max_us),
            l2p_multi_get_tree_us: load(&self.l2p_multi_get_tree_us),
            l2p_multi_get_tree_max_us: load(&self.l2p_multi_get_tree_max_us),
            flush_calls: load(&self.flush_calls),
            flush_calls_steady: load(&self.flush_calls_steady),
            flush_calls_forced: load(&self.flush_calls_forced),
            flush_total_us: load(&self.flush_total_us),
            flush_total_max_us: load(&self.flush_total_max_us),
            flush_total_us_steady: load(&self.flush_total_us_steady),
            flush_total_max_us_steady: load(&self.flush_total_max_us_steady),
            flush_total_us_forced: load(&self.flush_total_us_forced),
            flush_total_max_us_forced: load(&self.flush_total_max_us_forced),
            flush_gate_wait_us: load(&self.flush_gate_wait_us),
            flush_gate_wait_max_us: load(&self.flush_gate_wait_max_us),
            flush_gate_hold_us: load(&self.flush_gate_hold_us),
            flush_gate_hold_max_us: load(&self.flush_gate_hold_max_us),
            flush_dedup_drain_us: load(&self.flush_dedup_drain_us),
            flush_dedup_drain_max_us: load(&self.flush_dedup_drain_max_us),
            flush_l2p_fold_us: load(&self.flush_l2p_fold_us),
            flush_l2p_fold_max_us: load(&self.flush_l2p_fold_max_us),
            flush_sample_us: load(&self.flush_sample_us),
            flush_sample_max_us: load(&self.flush_sample_max_us),
            flush_sample_us_steady: load(&self.flush_sample_us_steady),
            flush_sample_max_us_steady: load(&self.flush_sample_max_us_steady),
            flush_sample_us_forced: load(&self.flush_sample_us_forced),
            flush_sample_max_us_forced: load(&self.flush_sample_max_us_forced),
            flush_sample_lock_us: load(&self.flush_sample_lock_us),
            flush_sample_lock_max_us: load(&self.flush_sample_lock_max_us),
            flush_sample_l2p_walk_us: load(&self.flush_sample_l2p_walk_us),
            flush_sample_l2p_walk_max_us: load(&self.flush_sample_l2p_walk_max_us),
            flush_sample_rc_drain_us: load(&self.flush_sample_rc_drain_us),
            flush_sample_rc_drain_max_us: load(&self.flush_sample_rc_drain_max_us),
            flush_rc_fold_lock_wait_us: load(&self.flush_rc_fold_lock_wait_us),
            flush_rc_fold_lock_wait_max_us: load(&self.flush_rc_fold_lock_wait_max_us),
            flush_rc_fold_service_us: load(&self.flush_rc_fold_service_us),
            flush_rc_fold_service_max_us: load(&self.flush_rc_fold_service_max_us),
            flush_rc_stream_calls: load(&self.flush_rc_stream_calls),
            flush_rc_stream_pages: load(&self.flush_rc_stream_pages),
            flush_rc_stream_service_us: load(&self.flush_rc_stream_service_us),
            flush_rc_stream_max_chunk_us: load(&self.flush_rc_stream_max_chunk_us),
            flush_rc_stream_max_chunk_pages: load(&self.flush_rc_stream_max_chunk_pages),
            flush_io_us: load(&self.flush_io_us),
            flush_io_max_us: load(&self.flush_io_max_us),
            flush_io_seal_us: load(&self.flush_io_seal_us),
            flush_io_seal_max_us: load(&self.flush_io_seal_max_us),
            flush_io_page_write_us: load(&self.flush_io_page_write_us),
            flush_io_page_write_max_us: load(&self.flush_io_page_write_max_us),
            flush_io_rc_meta_us: load(&self.flush_io_rc_meta_us),
            flush_io_rc_meta_max_us: load(&self.flush_io_rc_meta_max_us),
            flush_io_sync_us: load(&self.flush_io_sync_us),
            flush_io_sync_max_us: load(&self.flush_io_sync_max_us),
            flush_manifest_us: load(&self.flush_manifest_us),
            flush_manifest_max_us: load(&self.flush_manifest_max_us),
            flush_manifest_stage_us: load(&self.flush_manifest_stage_us),
            flush_manifest_stage_max_us: load(&self.flush_manifest_stage_max_us),
            flush_manifest_publish_us: load(&self.flush_manifest_publish_us),
            flush_manifest_publish_max_us: load(&self.flush_manifest_publish_max_us),
            flush_manifest_cleanup_us: load(&self.flush_manifest_cleanup_us),
            flush_manifest_cleanup_max_us: load(&self.flush_manifest_cleanup_max_us),
            flush_publish_barrier_wait_us: load(&self.flush_publish_barrier_wait_us),
            flush_publish_barrier_wait_max_us: load(&self.flush_publish_barrier_wait_max_us),
            flush_install_us: load(&self.flush_install_us),
            flush_install_max_us: load(&self.flush_install_max_us),
            flush_reclaim_us: load(&self.flush_reclaim_us),
            flush_reclaim_max_us: load(&self.flush_reclaim_max_us),
            flush_pages_written: load(&self.flush_pages_written),
            flush_reclaim_budget_pages: load(&self.flush_reclaim_budget_pages),
            flush_reclaim_selected_pages: load(&self.flush_reclaim_selected_pages),
            flush_reclaim_reclaimed_pages: load(&self.flush_reclaim_reclaimed_pages),
            flush_reclaim_blocked_pages: load(&self.flush_reclaim_blocked_pages),
            async_reclaim_cycles: load(&self.async_reclaim_cycles),
            async_reclaim_selected_pages: load(&self.async_reclaim_selected_pages),
            async_reclaim_reclaimed_pages: load(&self.async_reclaim_reclaimed_pages),
            async_reclaim_cycle_us: load(&self.async_reclaim_cycle_us),
            async_reclaim_cycle_max_us: load(&self.async_reclaim_cycle_max_us),
            lineage_gc_head_advanced: load(&self.lineage_gc_head_advanced),
            lineage_gc_head_dead_pbas: load(&self.lineage_gc_head_dead_pbas),
            lineage_gc_head_skipped_snap: load(&self.lineage_gc_head_skipped_snap),
            lineage_gc_head_skipped_descendant: load(&self.lineage_gc_head_skipped_descendant),
            lineage_gc_head_skipped_rc: load(&self.lineage_gc_head_skipped_rc),
            lineage_gc_head_blocked_rc0_pbas: load(&self.lineage_gc_head_blocked_rc0_pbas),
            lineage_gc_head_dropped_dedup_shared: load(&self.lineage_gc_head_dropped_dedup_shared),
            l2p_buffer_active_entries: load(&self.l2p_buffer_active_entries),
            l2p_buffer_compaction_cycles: load(&self.l2p_buffer_compaction_cycles),
            l2p_buffer_compaction_entries: load(&self.l2p_buffer_compaction_entries),
            l2p_buffer_compaction_us: load(&self.l2p_buffer_compaction_us),
            l2p_buffer_compaction_max_us: load(&self.l2p_buffer_compaction_max_us),
            l2p_buffer_compaction_leaves: load(&self.l2p_buffer_compaction_leaves),
            l2p_buffer_compaction_chunks: load(&self.l2p_buffer_compaction_chunks),
            l2p_buffer_compaction_plan_us: load(&self.l2p_buffer_compaction_plan_us),
            l2p_buffer_compaction_plan_max_us: load(&self.l2p_buffer_compaction_plan_max_us),
            l2p_buffer_compaction_tree_wait_us: load(&self.l2p_buffer_compaction_tree_wait_us),
            l2p_buffer_compaction_tree_wait_max_us: load(
                &self.l2p_buffer_compaction_tree_wait_max_us,
            ),
            l2p_buffer_compaction_apply_us: load(&self.l2p_buffer_compaction_apply_us),
            l2p_buffer_compaction_apply_max_us: load(&self.l2p_buffer_compaction_apply_max_us),
            l2p_buffer_compaction_publish_us: load(&self.l2p_buffer_compaction_publish_us),
            l2p_buffer_compaction_publish_max_us: load(&self.l2p_buffer_compaction_publish_max_us),
            l2p_buffer_compaction_finish_us: load(&self.l2p_buffer_compaction_finish_us),
            l2p_buffer_compaction_finish_max_us: load(&self.l2p_buffer_compaction_finish_max_us),
            l2p_prefold_attempts: load(&self.l2p_prefold_attempts),
            l2p_prefold_completed: load(&self.l2p_prefold_completed),
            l2p_prefold_skipped: load(&self.l2p_prefold_skipped),
            l2p_prefold_errors: load(&self.l2p_prefold_errors),
            l2p_prefold_us: load(&self.l2p_prefold_us),
            l2p_prefold_max_us: load(&self.l2p_prefold_max_us),
            l2p_prefold_wait_us: load(&self.l2p_prefold_wait_us),
            l2p_prefold_wait_max_us: load(&self.l2p_prefold_wait_max_us),
            l2p_buffer_lookup_hits: load(&self.l2p_buffer_lookup_hits),
            l2p_buffer_lookup_misses_to_tree: load(&self.l2p_buffer_lookup_misses_to_tree),
            l2p_buffer_backpressure_blocks: load(&self.l2p_buffer_backpressure_blocks),
            flush_sample_l2p_dirty_pages: load(&self.flush_sample_l2p_dirty_pages),
            flush_sample_l2p_dirty_pages_max: load(&self.flush_sample_l2p_dirty_pages_max),
            flush_sample_rc_drained_deltas: load(&self.flush_sample_rc_drained_deltas),
            flush_sample_rc_drained_deltas_max: load(&self.flush_sample_rc_drained_deltas_max),
            flush_sample_rc_fresh_pages: load(&self.flush_sample_rc_fresh_pages),
            flush_sample_rc_fresh_pages_max: load(&self.flush_sample_rc_fresh_pages_max),
            flush_sample_rc_staged_pages: load(&self.flush_sample_rc_staged_pages),
            flush_sample_rc_staged_pages_max: load(&self.flush_sample_rc_staged_pages_max),
            rc_drainer_cycles: load(&self.rc_drainer_cycles),
            rc_drainer_drained_entries: load(&self.rc_drainer_drained_entries),
            rc_drainer_pages_built: load(&self.rc_drainer_pages_built),
            rc_drainer_cycle_us: load(&self.rc_drainer_cycle_us),
            rc_drainer_cycle_max_us: load(&self.rc_drainer_cycle_max_us),
            rc_drainer_overlay_size_max_pages: load(&self.rc_drainer_overlay_size_max_pages),
            rc_drainer_checkpoint_wait_us: load(&self.rc_drainer_checkpoint_wait_us),
            rc_drainer_checkpoint_wait_max_us: load(&self.rc_drainer_checkpoint_wait_max_us),
            rc_drainer_backpressure_fallbacks: load(&self.rc_drainer_backpressure_fallbacks),
            rc_drainer_pool_refills: load(&self.rc_drainer_pool_refills),
            rc_drainer_wakes: load(&self.rc_drainer_wakes),
            rc_drainer_preempts: load(&self.rc_drainer_preempts),

            dedup_drainer_cycles: load(&self.dedup_drainer_cycles),
            dedup_drainer_drained_entries: load(&self.dedup_drainer_drained_entries),
            dedup_drainer_cycle_us: load(&self.dedup_drainer_cycle_us),
            dedup_drainer_cycle_max_us: load(&self.dedup_drainer_cycle_max_us),
            dedup_drainer_wakes: load(&self.dedup_drainer_wakes),
            dedup_drainer_preempts: load(&self.dedup_drainer_preempts),
            dedup_drainer_checkpoint_wait_us: load(&self.dedup_drainer_checkpoint_wait_us),
            dedup_drainer_checkpoint_wait_max_us: load(&self.dedup_drainer_checkpoint_wait_max_us),
            dedup_drainer_staged_active_max: load(&self.dedup_drainer_staged_active_max),
            dedup_drainer_backpressure_drains: load(&self.dedup_drainer_backpressure_drains),

            flush_io_bytes_total: load(&self.flush_io_bytes_total),

            meta_io_write_calls: load(&self.meta_io_write_calls),
            meta_io_write_ops: load(&self.meta_io_write_ops),
            meta_io_write_bytes: load(&self.meta_io_write_bytes),
            meta_io_write_us: load(&self.meta_io_write_us),
            meta_io_write_max_us: load(&self.meta_io_write_max_us),
            meta_io_write_batch_ops_max: load(&self.meta_io_write_batch_ops_max),
            meta_io_write_batch_bytes_max: load(&self.meta_io_write_batch_bytes_max),

            meta_io_read_calls: load(&self.meta_io_read_calls),
            meta_io_read_ops: load(&self.meta_io_read_ops),
            meta_io_read_bytes: load(&self.meta_io_read_bytes),
            meta_io_read_us: load(&self.meta_io_read_us),
            meta_io_read_max_us: load(&self.meta_io_read_max_us),
            meta_io_read_batch_ops_max: load(&self.meta_io_read_batch_ops_max),

            meta_io_fsync_calls: load(&self.meta_io_fsync_calls),
            meta_io_fsync_us: load(&self.meta_io_fsync_us),
            meta_io_fsync_max_us: load(&self.meta_io_fsync_max_us),

            meta_io_write_uring_lock_acquires: load(&self.meta_io_write_uring_lock_acquires),
            meta_io_write_uring_lock_wait_us: load(&self.meta_io_write_uring_lock_wait_us),
            meta_io_write_uring_lock_wait_max_us: load(&self.meta_io_write_uring_lock_wait_max_us),

            io_submitter_iterations: load(&self.io_submitter_iterations),
            io_submitter_sqes_submitted: load(&self.io_submitter_sqes_submitted),
            io_submitter_bg_deferred: load(&self.io_submitter_bg_deferred),
            io_submitter_bg_inflight_max: load(&self.io_submitter_bg_inflight_max),
            io_submitter_bg_deferred_max: load(&self.io_submitter_bg_deferred_max),
            io_submitter_channel_pending_max: load(&self.io_submitter_channel_pending_max),
            io_submitter_submit_batch_size_max: load(&self.io_submitter_submit_batch_size_max),
            io_submitter_inflight_max: load(&self.io_submitter_inflight_max),

            l2p_writeback_cycles: load(&self.l2p_writeback_cycles),
            l2p_writeback_cycles_with_work: load(&self.l2p_writeback_cycles_with_work),
            l2p_writeback_shards_flushed: load(&self.l2p_writeback_shards_flushed),
            l2p_writeback_pages_promoted: load(&self.l2p_writeback_pages_promoted),
            l2p_writeback_pages_kept_dirty: load(&self.l2p_writeback_pages_kept_dirty),
            l2p_writeback_pages_written: load(&self.l2p_writeback_pages_written),
            l2p_writeback_io_bytes_total: load(&self.l2p_writeback_io_bytes_total),
            l2p_writeback_seal_us: load(&self.l2p_writeback_seal_us),
            l2p_writeback_seal_max_us: load(&self.l2p_writeback_seal_max_us),
            l2p_writeback_io_us: load(&self.l2p_writeback_io_us),
            l2p_writeback_io_max_us: load(&self.l2p_writeback_io_max_us),
            l2p_writeback_install_us: load(&self.l2p_writeback_install_us),
            l2p_writeback_install_max_us: load(&self.l2p_writeback_install_max_us),
            l2p_writeback_errors: load(&self.l2p_writeback_errors),
            l2p_writeback_target_skips: load(&self.l2p_writeback_target_skips),
        }
    }
}
